### PR TITLE
data: clark: Allow ROMs to flash modem partition

### PR DESCRIPTION
**Pull request by chenxiaolong**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
Test build: https://jenkins.noobdev.io/job/DualBootPatcher_Build/319/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/

**Comment by webmaster33** [comment]
I really welcome the modern flashing feature. 
Does it work for all Android phones or support must be added separately?

**Comment by chenxiaolong** [comment]
@webmaster33 The only thing this does is allow ROM installers to flash a modem.

**Comment by webmaster33** [comment]
So separately installing a modem is not available at the moment?

**Pull request merged**
