### PR TITLE
Add Support for Huawei Mate 8

### PR DESCRIPTION
**Pull request by Kingzak34**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
The build failed due to:

```
huawei.yml: Failed to convert file: yaml-cpp: error at line 87, column 1: illegal tab when looking for indentation
```

It looks like there's some trailing whitespace on lines 87 and 88.

**Comment by Kingzak34** [comment]
Ok thanks for report I'll correct that tomorrow ASAP.

**Comment by Kingzak34** [comment]
Should be OK now.

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by Kingzak34** [comment]
Seems to be working OK.

**Pull request merged**
