### PR TITLE
Add Moto E4/plus Qcom variants

### PR DESCRIPTION
**Pull request by iykequame**
Moto E4 (Qualcomm)
Moto E4 Plus (Qualcomm)

### CODE REVIEW

**Comment by electricboy207** [comment]
Please add this, I would really like to use this on my perry e4.

**Comment by chenxiaolong** [comment]
@noobdev-bot test this please

**Comment by electricboy207** [comment]
I just tried it on my Perry, and sadly it crashes trying to start mbtool.

**Comment by chenxiaolong** [comment]
I'm pretty sure that's not related to this PR. It's probably the same crash as #986. If you could post the crash logs there, that would be great. I will be trying to fix that issue today.

**Pull request merged**
