### PR TITLE
9.1.0 Release

### PR DESCRIPTION
**Pull request by chenxiaolong**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
Test build: https://jenkins.noobdev.io/job/DualBootPatcher_Build/346/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/

**Comment by Caio99BR** [comment]
SONY Stock ROM 4.4.2 not boot with this version:
[last_kmsg.txt](https://github.com/chenxiaolong/DualBootPatcher/files/602258/last_kmsg.txt)

Not tested with old version

**Comment by chenxiaolong** [comment]
@Caio99BR Thanks! That should be fixed now. It was mounting filesystems with the `defaults` option, which is not valid.

**Comment by Caio99BR** [comment]
Thanks, no more issues. ;)

**Pull request merged**
