### PR TITLE
Add bootui for almost ALL Devices !

### PR DESCRIPTION
**Pull request by yshalsager**
I added bootui feature to all devices, get the info from each device twrp repository.
Devices without bootui: (I can't find their repo)
- 360 devices
- DEXP X LTE 4.5
- Umi Super
- Wiko Lenny 2

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@yshalsager Wow, thank you for taking the time to look at the TWRP repos for all of these devices!

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
```
17:40:30 [utilities] Schema validation failed:
17:40:30 [utilities] - Schema URI: #
17:40:30 [utilities] - Schema keyword: enum
17:40:30 [utilities] - Document URI: #/70/boot_ui/theme
17:40:30 [utilities] Parent of offending JSON value:
17:40:30 [utilities] {
17:40:30 [utilities]     "brightness_path": "/sys/class/leds/lcd-backlight/brightness",
17:40:30 [utilities]     "pixel_format": "RGBA_8888",
17:40:30 [utilities]     "graphics_backends": [
17:40:30 [utilities]         "fbdev"
17:40:30 [utilities]     ],
17:40:30 [utilities]     "max_brightness": 255,
17:40:30 [utilities]     "theme": "portrait_mdpi",
17:40:30 [utilities]     "cpu_temp_path": "/sys/devices/virtual/thermal/thermal_zone1/temp",
17:40:30 [utilities]     "default_brightness": 162,
17:40:30 [utilities]     "supported": true
17:40:30 [utilities] }
17:40:30 [utilities] make[2]: *** [data/devices/CMakeFiles/run_devicesgen.dir/build.make:117: data/devices/devices.json] Error 1
17:40:30 [utilities] make[2]: *** Deleting file 'data/devices/devices.json'
17:40:30 [utilities] make[2]: Leaving directory '/home/jenkins-slave/workspace/DualBootPatcher_Build@2/build_utilities'
17:40:30 [utilities] make[1]: *** [CMakeFiles/Makefile2:1542: data/devices/CMakeFiles/run_devicesgen.dir/all] Error 2
17:40:30 [utilities] make[1]: Leaving directory '/home/jenkins-slave/workspace/DualBootPatcher_Build@2/build_utilities'
17:40:30 [utilities] make: *** [Makefile:163: all] Error 2
```
It looks like the build failed. There are 3 devices with the theme set to `portrait_mdpi`. Unfortunately, this won't work because DualBootPatcher doesn't have that theme: https://github.com/chenxiaolong/DualBootPatcher/tree/master/mbbootui/theme

**Comment by Caio99BR** [comment]
Can you remove bootui support of Xperia E1? It currently don't work (#412) and I forget to remove (also I'm lazy to do it :P)

**Comment by yshalsager** [comment]
@chenxiaolong all requested changes has been made.
I need to contact you, Can you reply my XDA message or Can i use any another way?
There's some things about DBP i need to tell you about.
like this https://hub.docker.com/r/yshalsager/dualbootpatcher/tags/
I am building and uploading docker images since release 9.2.0-2 😄

**Comment by yshalsager** [comment]
@Caio99BR i removed it as you requested https://github.com/chenxiaolong/DualBootPatcher/pull/798/commits/b4ab55ad04940943def96e648f6f0ebb5fbe48ac

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by Caio99BR** [comment]
Thanks :)

**Pull request merged**
