### PR TITLE
Add support to coolpad

### PR DESCRIPTION
**Pull request by meudayhegde**
Please add support coolpad note 3 , note 3 lite and note 3 plus.
I have tested this patch by edoting devices.json file everything working fine.
only backup rom is not working

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
The build failed due to this error:

```
coolpad.yml: Failed to convert file: yaml-cpp: error at line 2, column 8: illegal map value
```

It looks like you have an extra space at the beginning of every line.

**Comment by meudayhegde** [comment]
fixed space before each line

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Pull request merged**
