### PR TITLE
Add support - Lenovo K4 Note

### PR DESCRIPTION
**Pull request by ashoksoni**
- name: Lenovo K4 Note
  id: A7010a48
  codenames:
    - A7010a48
    - K4
    - K4 Note
    - Lenovo K4 Note
    - Vibe X3 Lite
    - Lenovo A7010a48

lenovo.yml provided by dg28gadhavi@xda

Build was successful.

### CODE REVIEW

**Comment by dg28gadhavi** [comment]
Hey i am trying to compile debug apk can you help me how to resolve one error at last while executing make apk command i am getting error something like hashtag android 25 not found in android ndk @ashoksoni

**Comment by dg28gadhavi** [comment]
Android 25 platform is still not available for ndk i am latest beta

**Comment by ashoksoni** [comment]
You need to update your sdk, not ndk.

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Pull request merged**
