### PR TITLE
add sony xperia sp support

### PR DESCRIPTION
**Pull request by darjwx**
I am pretty sure this will work but I could not test it due to some errors with CMake. Could you build the app with my commit so I could test it?. Only if you want/can :). Thanks anyway.

### CODE REVIEW

**Comment by chenxiaolong** [comment]
Sure, let's have the build server make a build :)

@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
@darjwx The build failed: https://jenkins.noobdev.io/job/DualBootPatcher_Build/50/

You can check the build logs by clicking a build target:

(screenshot)
image

and then clicking "Console Output" in the left sidebar.

**Comment by darjwx** [comment]
Okay, I will check it.

**Comment by darjwx** [comment]
@chenxiaolong now should be fine with the test commit.

**Comment by darjwx** [comment]
My problems with cmake are now fixed. I will build the apk to test it. I will make other pull request when tested :)

**Comment by darjwx** [comment]
Well, I don't want to bother you, I'm having problems to build it. (I have experience building ROMs, not apk). Could you build it?

**Pull request closed without merging**
