### PR TITLE
Added Support For Micromax Unite 2 A106 (MTK)

### PR DESCRIPTION
**Pull request by manjotsidhu**
Added Support For Micromax Unite 2 A106 - MT6582 ...

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
```
18:06:01 [utilities] Schema validation failed:
18:06:01 [utilities] - Schema URI: #
18:06:01 [utilities] - Schema keyword: pattern
18:06:01 [utilities] - Document URI: #/96/block_devs/cache/1
18:06:01 [utilities] Parent of offending JSON value:
18:06:01 [utilities] [
18:06:01 [utilities]     "/dev/block/platform/mtk-msdc.0/by-name/cache",
18:06:01 [utilities]     "/emmc@cache"
18:06:01 [utilities] ]
```
Can you please remove the `/emmc` paths? DBP doesn't support those.

**Comment by manjotsidhu** [comment]
Removed ...

**Comment by manjotsidhu** [comment]
done ...

**Comment by kutlay1653** [comment]
Any update?

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Pull request merged**
