### PR TITLE
Add initial support for Sony devices using combined boot/recovery ramdisk

### PR DESCRIPTION
**Pull request by chenxiaolong**
This implements initial support for the combined boot and recovery ramdisks that Sony uses. This currently only works for AOSP-based ROMs that have `/sbin/init.sh` in the ramdisk. (Though I haven't tested this yet since I don't have a Sony device.)

In-app flashing should also work now. Since it needs to load files from recovery, it will try to read the `FOTAKernel` partition if it is provided (see below). Otherwise, it will use the recovery ramdisk bundled in `boot.img`.

Any Sony device that uses a combined image must have the following two lines specified in the device file:

```cpp
device->setFlags(Device::FLAG_HAS_COMBINED_BOOT_AND_RECOVERY);
device->setRamdiskPatcher(XperiaDefaultRP::Id);
```

In addition, I strongly recommend setting the recovery path to the `FOTAKernel` partition since it appears that many (most?) AOSP-based ROMs will load the recovery from that partition instead of the bundled one in `boot.img`.

Tagging: @Caio99BR @darjwx @zhuoyang

### CODE REVIEW

**Comment by chenxiaolong** [comment]
The test build will be available here when it finished building: https://jenkins.noobdev.io/job/DualBootPatcher_Build/60/

**Comment by Caio99BR** [comment]
But the test build not deploy the files, we will need build it

**Comment by darjwx** [comment]
Okay, I will adapt my changes based on this.

**Comment by chenxiaolong** [comment]
@Caio99BR The builds are always available to download from Jenkins (because only master branch is deployed). You just have to click the appropriate build configuration link first:

(Screenshot)
image

**Comment by Caio99BR** [comment]
Ok, i found it.
Not worked, idk why, no change (i not can grab logcat now).
Ps: in falconss sony devs made the system mount in init (it is like f*** fstab, you not are made for this).
Ps2: maybe the problem not is this.

**Comment by Caio99BR** [comment]
Ps3: the screen get blank because a command before run recovery, this in app, only restarting system, good.

**Comment by Caio99BR** [comment]
Ps4: i can flash files, but this fail to boot (that vibration not work, only in some devices).
Ps5: mbtool and romid is on ramdisk but no usage?
Ps6: if you check init.sh you can see the script delete /init (himself) and start /init from ramdisk
Ps7: the problem of withe screen will be solved soon, i thing i need to use prerecovery.sh not dependency of init.sh.
Ps8: i like Ps :)

**Comment by Caio99BR** [comment]
Just in case @chenxiaolong check this https://github.com/blog/2111-issue-and-pull-request-templates, new in github

**Comment by chenxiaolong** [comment]
@Caio99BR 

> Ps5: mbtool and romid is on ramdisk but no usage?
> Ps6: if you check init.sh you can see the script delete /init (himself) and start /init from ramdisk
> Ps7: the problem of withe screen will be solved soon, i thing i need to use prerecovery.sh not dependency of init.sh.

Could you check what's in the bottom of the "init.sh" file? The

```sh
exec /init
```

should have been replaced with:

```sh
if [ -f /sbin/recovery ]; then
    exec /init
else
    exec /mbtool init
fi
```

so mbtool will run mbtool when booting normally and run /init when booting to recovery.

> Ps8: i like Ps :)

:laughing:

**Comment by Caio99BR** [comment]
No change in init.sh, this is allocated in /sbin/init.sh in most of cases.
In Xperia E1 the init.sh is untouched.

**Comment by chenxiaolong** [comment]
@Caio99BR Using the test build and patching your ROM (http://forum.xda-developers.com/xperia-e1/orig-development/rom-cyanogenmod-11-xperia-e1-t3327565) for falconss, it successfully replaced the `exec /init` in `/sbin/init.sh` for me.

```
chenxiaolong@cxl-4270cto: /stuff/Android/DualBoot/SonyXperiaE1/cm-11-20160302-UNOFFICIAL-falconss_primary/temp
 $ tail -5 sbin/init.sh                                                                                                                                                                                                            [14:54:25]
if [ -f /sbin/recovery ]; then
    exec /init
else
    exec /mbtool init
fi
```

**Comment by Caio99BR** [comment]
image
Here the patched ramdisk of stock.

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by Caio99BR** [comment]
@chenxiaolong still not working, i need to upload any log?

(Why God? WHY?)(/sbin/init.sh is untouched)

**Comment by chenxiaolong** [comment]
> @chenxiaolong still not working, i need to upload any log?
> 
> (Why God? WHY?)(/sbin/init.sh is untouched)

Can you check the symlink path of `init`? Does it point to `/sbin/init.sh` or `sbin/init.sh`? I wonder if that's the issue since the code expect it to be the latter case.

**Comment by Caio99BR** [comment]
This point to `sbin/init.sh` in init symlink but the local is `/sbin/init.sh` because this call `init` is called on `/`, nothing special at here, i think.

**Comment by chenxiaolong** [comment]
> @Caio99BR This point to `sbin/init.sh` in init symlink but the local is `/sbin/init.sh` because this call `init` is called on `/`, nothing special at here, i think. 

Could you link me to the ROM or boot.img? I can't seem to reproduce this on any ROM I've downloaded.

**Comment by Caio99BR** [comment]
> Could you link me to the ROM or boot.img? I can't seem to reproduce this on any ROM I've downloaded.

https://github.com/Caio99BR/FalconSSKernel/releases

> EDIT: If you are free right now, feel free to ping me on Google Hangouts: andrewgunnerson AT gmail.com

Sent.

**Comment by Caio99BR** [comment]
Any way to rebase it?
And if possible, you can add a way to deal with mount's inside .rc files?
Because Stock KitKat of Xperia E1 use it https://github.com/TeamVee-SS/android_device_sony_falconss/commit/46232998c2deb188dcecb8bdf4cab42dcfdf7772#diff-1645868b288db566c8947c10a7f412d1R15 and may make things bad, no?

**Comment by Caio99BR** [comment]
Any way to test it on #137?
The build 60 is deleted of Jenkins, and i cant test

**Pull request closed without merging**
