### PR TITLE
Add support for GM4G

### PR DESCRIPTION
**Pull request by chenxiaolong**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
Test build: https://jenkins.noobdev.io/job/DualBootPatcher_Build/216/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/

**Comment by wazeeahmed** [comment]
@MSF-Jarvis Try it at once and let @chenxiaolong know .

**Comment by arvinquilao** [comment]
@chenxiaolong I ran the test build and encountered these errors:

primary ROM: CM-13.0 unofficial
ROM to be flashed: CM-13.0 unofficial (different build date)
multiboot.log: http://hastebin.com/eqazovodil.sql

ROM to be flashed: CM-14.0 unofficial
multiboot.log: http://hastebin.com/okagumaseb.sql

**Comment by chenxiaolong** [comment]
@arvinquilao Oh, that seems like an easy fix. Can you flash the GetLogs zip at https://snapshots.noobdev.io and attach the file it creates in /sdcard/logs/ here?

**Comment by arvinquilao** [comment]
Here you go. First one is via in-app flashing. 2nd file is the log when TWRP was used.
[20161005.121720.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/515093/20161005.121720.tar.gz)
[20161005.122722.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/515094/20161005.122722.tar.gz)

**Pull request closed without merging**
