### PR TITLE
data: Add support for lettuce

### PR DESCRIPTION
**Pull request by out386**
Could you please do a test build? I couldn't build it myself.

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please _(This is a message for the build server)_

@out386 Sure, I'll edit this post and link to the test build once it's built.

**Comment by out386** [comment]
Thanks. And sorry about that. Fixed it.

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
@out386 Thanks! A new test build is available at: https://jenkins.noobdev.io/job/DualBootPatcher_Build/356/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/

**Comment by out386** [comment]
I'm getting this, even  though /dev/block/bootdevice/by-name/* does exist. 

http://hastebin.com/egecohufik.sql

**Comment by out386** [comment]
Could you please build this as well? I just can't get the build environment working on my PC.

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
@out386 New test build: https://jenkins.noobdev.io/job/DualBootPatcher_Build/408/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/

**Comment by out386** [comment]
This build is giving me the same errors as the last build. I'm sorry if I'm wrong, but does it include my last commit? Because I couldn't find it in the list of changes. 😅

This build appears to have the correct commit, but it failed:

https://jenkins.noobdev.io/job/DualBootPatcher_Build/407/console

Did I mess something up again? 😅

**Comment by chenxiaolong** [comment]
The build I linked is correct :) If you look at the bottom of the devices.json file linked there, you'll see your latest changes to the paths. Unfortunately, because the build server builds from a bunch of different branches, the commit list is not always correct.

As for the error, can you post the log? Are you sure you repatched the file?

**Comment by out386** [comment]
Oh, sorry.
The log is the same as the previous one, here:
http://hastebin.com/egecohufik.sql

Yes, I did patch the file. 

When I try to flash, the updater-script says that the zip is for "YUPHORIA, this is lettuce". I did set the first codename to YUPHORIA. Does the device codename get set by the 'id' variable, or by the 1st string in the codenames array?

I changed the assert in the zip, now it starts flashing, but stops without specifying a reason. The log is above. It says that /dev/block/bootdevice/by-name/system was not found, but it does exist on the device.

**Comment by chenxiaolong** [comment]
> Oh, sorry.
> The log is the same as the previous one, here:
> http://hastebin.com/egecohufik.sql
> 
> Yes, I did patch the file.

Hmm, that's very strange. Your latest change definitely should have fixed the path issue.

> When I try to flash, the updater-script says that the zip is for "YUPHORIA, this is lettuce". I did set the first codename to YUPHORIA. Does the device codename get set by the 'id' variable, or by the 1st string in the codenames array?

The patcher does not change the value, so it uses whatever is set in `/system/build.prop` (if you use in-app flashing) or `/default.prop` (if you flash from recovery). The `id` and `codename` variables are for the patcher's own checks and do not affect the updater-script.

> I changed the assert in the zip, now it starts flashing, but stops without specifying a reason. The log is above. It says that /dev/block/bootdevice/by-name/system was not found, but it does exist on the device.

Can you try clearing the app data before repatching the file? After your latest change, the log should have the following at around line 28 (or at least an error message):

<pre>
<b>[D] Symlinked /mb/loop.system to /dev/block/bootdevice/by-name/system</b>
[D] Symlinked /mb/loop.system to /chroot/dev/block/platform/soc.0/7824900.sdhci/by-name/system
[D] Symlinked /mb/loop.system to /chroot/dev/block/mmcblk0p22
</pre>

> Also, another thing. Can I test my fixes by simply editing the devices.json in a built apk after untaring the data.tar.xz? 😅 'cause I just can't get past the cmake and toolchain errors.

If you edit the apk directly, it will no longer work for any privileged operations, like switching ROMs and flashing things, because the APK signature is checked. However, you should be able to edit `/data/data/com.github.chenxiaolong.dualbootpatcher.snapshot/files/data-<VERSION>/data/devices.json` directly. Just remember to restart the app after you change the file 🙂

**Comment by out386** [comment]
Yes, it's finally working :) Booted successfully to a secondary ROM.
Didn't realize that I had to clear data before patching. 

There are still two issues, though. Assert still keeps failing, though my build.prop and recovery's default.prop both have codename set to YUPHORIA. To be safe, I also changed the "lettuce" s in the JSON to "YUPHORIA", but assert still fails.

And the bootui is a bit unstable. It works, but it reboots 2-3 times before finally booting to the ROM I want. But this device sometimes reboots a few times anyway, before booting to a ROM, even without Dualbootpatcher, so I'm not sure if it's even a real problem.

I can't seem to fix the assert, however ;_;

**Comment by chenxiaolong** [comment]
@out386 Clearing the data is only necessary if the version number didn't increase between the test builds.

Can you post both the build.prop and the updater-script?

**Comment by out386** [comment]
[build.prop.txt](https://github.com/chenxiaolong/DualBootPatcher/files/617860/build.prop.txt)
[updater-script.txt](https://github.com/chenxiaolong/DualBootPatcher/files/617861/updater-script.txt)

Here are the files. 

I tested the bootui a bit more, and I realized that it keeps rebooting right after the countdown reaches 3, unless I cancel, tap switch rom, and select the primary ROM. Then it boots. But that doesn't matter much, so 😅

**Comment by chenxiaolong** [comment]
I'm really not sure what's going on with the assert. In line 17 of your first log, it seems like it correctly detects `ro.product.device = YUPHORIA`: http://hastebin.com/egecohufik.sql

Can you give `9.1.0.r9.g8558828` at https://dbp.noobdev.io a try? I changed it print out all the properties to the log file right before running the installer. Thanks!

**Comment by out386** [comment]
[Multiboot .log.txt](https://github.com/chenxiaolong/DualBootPatcher/files/618644/Multiboot.log.txt)

Here's the log. This is so weird, it is picking the right codename, but it's failing anyway.

**Comment by out386** [comment]
@chenxiaolong, anything on this assert thingy? Or should I open a new issue?

**Pull request merged**
