### PR TITLE
libmbp/paths: add paths defines for qcom sd-615

### PR DESCRIPTION
**Pull request by onano**

### CODE REVIEW

**Comment by TheScarastic** [comment]
sd615 also uses different path to base dir like in marshmallow and lollipop like sd810 so either add both or close this

**Comment by TheScarastic** [comment]
@chenxiaolong can you please help how to tackle the issue of dualbooting the lp and mm roms when base dir changes :(

**Comment by onano** [comment]
@TheScarastic Yes, i know for mm they changed to soc.0 paths, but i don't have proper defines available at my disposal for Marshmallow (My device only have marshmallow sadly), if you have specific path available please direct me and i'll add it

**Comment by chenxiaolong** [comment]
@TheScarastic I don't have any device where the base directory changed in newer versions of Android, but unless there is a bug, it should be enough to simply include both paths (eg. https://github.com/chenxiaolong/DualBootPatcher/blob/master/libmbp/devices/nexus.cpp#L65).

**Comment by TheScarastic** [comment]
@chenxiaolong I have to take care of 3 base dirs :( 

1) bootdevice_base dir (used up in updaterscript of all roms)
2) dev/block/platform/7824900.sdhci/by-name (used up in lollipop roms)
3)dev/block/platform/soc.0/7824900.sdhci/by-name (used in marshmallow roms)

i tried to add all but then patching fails but if add only 2 either bootdevice and lp base dir it works fine in lp roms and if i add bootdevice and mm base then it works fine in mm roms so please try to help :(

**Comment by thewisenerd** [comment]
@TheScarastic , is the behaviour of creating those namespaces defined in the kernel, or in the ROM side?

**Comment by TheScarastic** [comment]
@thewisenerd it's in rom only,kernel cannot control it :(

**Comment by chenxiaolong** [comment]
@TheScarastic

> i tried to add all but then flash fails but if I add only 2 either bootdevice and lp base dir it works fine in lp roms and if i add bootdevice and mm base then it works fine in mm roms so please try to help :(

Can you post the logs for the failed flash? That's a bug and I'd rather fix it than add any workarounds.

@thewisenerd: It's part of the ROM, but specifically, it's controlled by `/sbin/ueventd` in the boot image's ramdisk (so some people may consider it to be part of the kernel). The kernel exposes device events through the `uevent` files in `/sys`. ueventd reads these files and then creates the appropriate paths in `/dev`.

**Comment by TheScarastic** [comment]
@chenxiaolong https://drive.google.com/file/d/0BzSUCnmb8JlBOUdibjMwNkRyWE0/view?usp=docslist_api

logs are here i tried to understand them but could'nt find any error

**Comment by TheScarastic** [comment]
@chenxiaolong  could u please see

**Comment by chenxiaolong** [comment]
@TheScarastic: The error is in `MultiBoot.log`:

    [D] Child killed with signal: 11

Something is causing the ROM's installer to segfault. I'd suggest trying the installation-rework branch (https://github.com/chenxiaolong/DualBootPatcher/tree/installation-rework) and see if it makes a difference.

**Comment by thewisenerd** [comment]
@TheScarastic, @chenxiaolong; could it help if we say, added symlinks to the old paths *somehow* ?

**Comment by chenxiaolong** [comment]
@thewisenerd: Just to be clear, are you suggesting something like this? Lets say, a device's system partition is at:

* /dev/a (in KitKat)
* /dev/b (in Lollipop)
* /dev/c (in Marshmallow)

If any one of the paths exists (eg. /dev/b), then the remaining paths should be symlinks to the path that exists.

**Comment by TheScarastic** [comment]
@chenxiaolong tried  that branch too still issue persists :(

**Comment by TheScarastic** [comment]
@chenxiaolong just noticed that lollipop roms are getting flashed there is some issue with mm roms :?

**Comment by thewisenerd** [comment]
@chenxiaolong ; yes. Whichever exists, say ```/dev/b``` exists, the remaining two ```/a``` and ```/c``` should also be created.

**Comment by chenxiaolong** [comment]
@TheScarastic Do you have the MultiBoot.log file for the Marshmallow failure?

**Comment by chenxiaolong** [comment]
@thewisenerd I thought about the issue a little bit and besides the recovery partition (which is needed for in-app flashing), the installer should never access any partition directly. The system, cache, and data paths are only used when patching the file (used to determine the appropriate mount and unmount commands).

None of the system, cache, and data paths are available in the installation environment (usually).

**Comment by TheScarastic** [comment]
@chenxiaolong after experimenting a bit i got to know issue is in updater script of marshmallow roms, when i tried to replace updater script of mm roms with lp roms it got flashed and we could switch too (as updater script is using bootdevice partition, no issue arised)  

the above logs were for mm faliure only :)

**Comment by TheScarastic** [comment]
i will attach updater script here shortly so you could figure out what might be tge issue ;)

**Comment by chenxiaolong** [comment]
Thanks! If you could post both the working and non-working ones so I could compare them, that would be great :)

**Comment by TheScarastic** [comment]
@chenxiaolong  here are these 
https://app.box.com/s/3zvhvnkqwsc9nqu57rvcfottqhejml5b (working updaterscript) 
https://app.box.com/s/oq9ppup0neyeon7cwohx5du9fit3ufz1 (non-working updater script)

**Comment by chenxiaolong** [comment]
Hmm, what do the files look like in the zip? Does it have `system.new.dat` or simply a `system` folder with all the files inside? It seems like the broken updater-script is for the first case and the working updater-script is for the second case.

**Comment by TheScarastic** [comment]
@chenxiaolong update script is not broken coz if we flash cm13 roms without patching through recovery it gets flashed :(

**Comment by thewisenerd** [comment]
@chenxiaolong , if you say we just need the links to the partitions for mounting/unmounting, and is used only for patching zip files, can't we in some way, figure out if a ZIP is kitkat, or lollipop or marshmallow, and patch it appropriately?

This should be fairly easy for ROM zips not considering other zips like gapps or system patches...

**Comment by TheScarastic** [comment]
@thewisenerd thats indeed a good suggestion but lets see how would @chenxiaolong tackle this issue ;)

**Comment by chenxiaolong** [comment]
@thewisenerd That is already what's happening :)

If, for example, you have:

    device->setSystemBlockDevs({ "/dev/block/kitkat", "/dev/block/lollipop", "/dev/block/marshmallow" });

and the updater-script contains:

    format("ext4", "EMMC", "/dev/block/kitkat", "0", "/system");
    format("ext4", "EMMC", "/dev/block/lollipop", "0", "/system");
    format("ext4", "EMMC", "/dev/block/marshmallow", "0", "/system");

Then the result is:

    (run_program("/update-binary-tool", "format", "/system") == 0);
    (run_program("/update-binary-tool", "format", "/system") == 0);
    (run_program("/update-binary-tool", "format", "/system") == 0);

That's what I meant in my previous comment. Besides for editing the updater-script, the system, cache, and data paths are not used anywhere, so I don't know how it could cause problems.

@TheScarastic Do you have a link to the original zip file (for the failing CM13) that I could take a look at?

**Comment by TheScarastic** [comment]
@chenxiaolong  here is the link 

https://www.androidfilehost.com/?fid=24369303960688475

**Comment by thewisenerd** [comment]
@chenxiaolong so the ramdisk will contain the appropriate ```/dev/block/kitkat```, or ```/dev/block/lollipop``` or ```/dev/block/marshmallow``` depending upon the ramdisk that's being patched (or more precisely rewording it, depending upon if the boot.img is for kitkat, or lollipop or marshmallow)?

**Comment by chenxiaolong** [comment]
@thewisenerd The ramdisk is not changed with regards to the paths. It simply reads the `/fstab` file the same way that Android does.

**Comment by chenxiaolong** [comment]
@TheScarastic So I just flashed it on my old Galaxy S4 (changed "YUREKA" to "jfltetmo" and updated paths to `/dev/block/platform/msm_sdcc.1/by-name/...`) and it successfully flashed on my device. I'm using the `installation-rework` branch (you might need to `git pull --rebase`). I'm really not sure why it's not working for you.

[blah](http://i.imgur.com/1PFA4Q7.png)

(The failure occured simply because your boot.img is too large to fit on my device, but ROM itself flashed correctly)

**Comment by TheScarastic** [comment]
@chenxiaolong will try again and yes a strange thing is that a error comes "cant mount as ro"

**Comment by chenxiaolong** [comment]
@TheScarastic One thing I just thought of: not sure if this is causing the issue, but did you add the following line to the device code so it knows the device is 64 bit?

    device->setArchitecture(ARCH_ARM64_V8A);

**Comment by TheScarastic** [comment]
@chenxiaolong its there :'( ,really fed up , and yes cloned your work and did a build from scratch still its not getting flashed

**Comment by chenxiaolong** [comment]
@TheScarastic Darn :( Is the log file still showing the same crash as before?

    [D] Child killed with signal: 11

**Comment by TheScarastic** [comment]
yes @chenxiaolong :((((

**Comment by TheScarastic** [comment]
http://pastebin.com/NrhrhMNy
here is the latest

**Comment by chenxiaolong** [comment]
@TheScarastic Does it work if you flash from recovery instead of using in-app flashing?

**Comment by TheScarastic** [comment]
@chenxiaolong nope it doesn't get flashed through recovery too,  if we dont patch it and flash then it works  :((

**Comment by TheScarastic** [comment]
@chenxiaolong did you figured out something :(

**Comment by Caio99BR** [comment]
Can someone close this Pull Request and open a Issue if nothing solved?

**Pull request closed without merging**
