### PR TITLE
Added support for Energy Phone Colors and vodafone smart4

### PR DESCRIPTION
**Pull request by tone361**
Please add support for energy phone colors and vodafone smart 4

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by tone361** [comment]
Hi did the build finished?

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
@tone361 The build failed. In CMakeLists.txt, you have `energy_system.yml`, but the filename is `energy_sistem.yml`.

**Comment by tone361** [comment]
edit the file and enter energy_sistem

**Comment by chenxiaolong** [comment]
I'm closing this because:
* The syntax in the yaml files is not correct. Please verify the syntax with a website like https://codebeautify.org/yaml-validator
* The codenames in `energy_sistem.yml` are incorrect. I'm not sure why `MediaTek`, `Phone`, and `samsung` are in the list. The codenames should match `ro.product.device` in your device's `build.prop` file.

**Pull request closed without merging**
