### PR TITLE
devices: hydrogen: Add Marshmallow block device paths

### PR DESCRIPTION
**Pull request by TechExhibeo**
http://pastebin.com/vBbcsG6V

Signed-off-by: Deepak Sharma <TechExhibeo@gmail.com>

### CODE REVIEW

**Comment by TechExhibeo** [comment]
Multiboot.log 
http://pastebin.com/S6u9KQ1C

**Comment by chenxiaolong** [comment]
Instead of replacing the path, can you just add the new one? Both paths will exist depending on which version of Android you're running.

**Comment by TechExhibeo** [comment]
this path doesn't exist on hydrogen  > /dev/block/platform/7824900.sdhci/by-name


this one is from Marshmallow Stock ROM > /dev/block/platform/soc.0/7824900.sdhci/by-name
and same path is used by custom MM and N ROM's too ^

**Comment by Caio99BR** [comment]
Last message from me: Could be rebased or closed

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Pull request merged**
