### PR TITLE
libmbp: Add graphicsBackends for VEGA IRON 2

### PR DESCRIPTION
**Pull request by chautruongthinh**
Add graphicsBackends=overlay

### CODE REVIEW

**Comment by chautruongthinh** [comment]
I tried to use fbdev but it not work with my device, please help me fix it!!

> failed to mmap framebuffer: Invalid argument
fbdev: Initialization failed
Failed to load any backend
fb0 reports (possibly inaccurate):

**Comment by hankching** [comment]
Currently, you are using overlay, not fbdev.

Pls show the whole setting for UI section. Maybe it can find the correct driver.

**Comment by chautruongthinh** [comment]
I tried with overlay graphic and get same error!!

> [V] Loading graphics system...
failed to mmap framebuffer: Invalid argument
fbdev: Initialization failed
Failed to load any backend
fb0 reports (possibly inaccurate):
  vi.bits_per_pixel = 32
  vi.red.offset   =  24   .length =   8
  vi.green.offset =  16   .length =   8
  vi.blue.offset  =   8   .length =   8
[E] Failed to load graphics system

**Comment by chautruongthinh** [comment]
you can see TWRP recovery.log of my device from here:
https://paste.omnirom.org/view/94e60492

**Comment by chautruongthinh** [comment]
you can see TWRP recovery.log of my device from here:
https://paste.omnirom.org/view/94e60492

**Comment by hankching** [comment]
Try this setting

    device->twOptions()->supported = true;
    device->twOptions()->flags = Device::FLAG_TW_QCOM_RTC_FIX;
    device->twOptions()->graphicsBackends = { "overlay_msm_old" };
    device->twOptions()->pixelFormat = Device::TwPixelFormat::RGBX_8888;
    device->twOptions()->maxBrightness = 255;
    device->twOptions()->defaultBrightness = 175;

**Comment by chautruongthinh** [comment]
Yeah!! It worked. Many thank @hankching!!

**Comment by hankching** [comment]
Patch zip for primary and flash it.

**Comment by chenxiaolong** [comment]
@chautruongthinh You will need to do a ramdisk update (if you haven't already) for the primary ROM. Otherwise, it won't know that the Boot UI should run.

**Comment by chautruongthinh** [comment]
@chenxiaolong

I updated ramdisk of primary rom. Boot UI only work with second rom

**Comment by chautruongthinh** [comment]
@hankching @chenxiaolong 
It worked great. Thank your support!!

**Pull request closed without merging**
