### PR TITLE
add XiaoMI Note Pro support

### PR DESCRIPTION
**Pull request by GuaiYiHu**
Add support to xiaomi note pro, thanks a lot for your good work!

### CODE REVIEW

**Comment by GuaiYiHu** [comment]
This device is just like MI-4c.

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by GuaiYiHu** [comment]
I have made some changes on NDK  tool version.......

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot retest this please

**Comment by chenxiaolong** [comment]
@GuaiYiHu

> I have made some changes on NDK tool version.......

I undid those changes in this PR because I already fixed the NDK version checks in another commit.

**Comment by GuaiYiHu** [comment]
Then I had to revert this change... So much sorry...

**Comment by GuaiYiHu** [comment]
I have released a test build for mi note lte, mi note pro and mi2/2s. It works very well.

**Pull request merged**
