### PR TITLE
Add support for YU Yunique

### PR DESCRIPTION
**Pull request by MSF-Jarvis**
Having issues with NDK just like @out386 

```

  x86_64-linux-android-g++: error: x86_64-none-linux-android: No such file or
  directory

  x86_64-linux-android-g++: error: x86_64-none-linux-android: No such file or
  directory

  x86_64-linux-android-g++: error: unrecognized command line option '-target'

  x86_64-linux-android-g++: error: unrecognized command line option '-target'

  x86_64-linux-android-g++: error: unrecognized command line option
  '-fno-limit-debug-info'

  make[4]: *** [CMakeFiles/cmTC_4c8ab.dir/testCXXCompiler.cxx.o] Error 1

  make[4]: Leaving directory
  `/root/harsh/DualBootPatcher/build/android/android-system_x86_64-prefix/src/android-system_x86_64-build/CMakeFiles/CMakeTmp'


  make[3]: *** [cmTC_4c8ab/fast] Error 2

  make[3]: Leaving directory
  `/root/harsh/DualBootPatcher/build/android/android-system_x86_64-prefix/src/android-system_x86_64-build/CMakeFiles/CMakeTmp'
```

### CODE REVIEW

**Comment by out386** [comment]
That log you gave is of the same problem I'm having.

**Comment by MSF-Jarvis** [comment]
> Having issues with NDK just like @out386

@out386 I mentioned that

**Comment by chenxiaolong** [comment]
Can you post some details about the environment so I can try to reproduce the issue?

- Distro version
- CMake version
- Android NDK version
- CMake command used

**Comment by MSF-Jarvis** [comment]
> Distro version
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety
```

> CMake version
`cmake version 3.7.0`

> Android NDK version

`android-ndk-r13b-linux-x86_64.zip`

> CMake command used

```
mkdir build && cd build
cmake .. \
   -DMBP_BUILD_TARGET=android \
   -DMBP_BUILD_TYPE=debug
make
rm -rf assets && cpack -G TXZ
make apk
```

**Comment by MSF-Jarvis** [comment]
Thanks, didn't have the device on hand when I did the PR so couldn't
traceback the symlinks to the real block entry

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
Test build: https://jenkins.noobdev.io/job/DualBootPatcher_Build/431/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/

**Comment by chenxiaolong** [comment]
@MSF-Jarvis @out386 The CMake 3.7 issues are now fixed in the master branch.

**Comment by MSF-Jarvis** [comment]
Thanks I'll try again. The test build works perfectly, so this is ready to merge :)

**Comment by chenxiaolong** [comment]
Merged. Thanks!

**Pull request merged**
