### PR TITLE
Added Oneplus 3T Support

### PR DESCRIPTION
**Pull request by kaise123**
The 3T uses identical partition Layout to the 3, so copied, confirmed same, edited names.

### CODE REVIEW

**Comment by VampireHeart** [comment]
I tried to make it working but on my Oneplus3t I can't set primary kernel and if I try to patch a file it end but also deleting the verify for model in update-script file the process of flashing stop.

**Comment by Startrek852** [comment]
DualBootPatcher has already been ported to the 3T: https://forum.xda-developers.com/oneplus-3t/themes/port-dualbootpatcher-multiboot-oneplus-t3567692

**Comment by VampireHeart** [comment]
Thanks i servizi that thread and try the app bit It don't recognise​ the primary kernel and the primary ROM. There is also another problem, on the thread say that is solved but not for me if i patch a ROM i must delete the string for the verify of device otherwise i can't flash, but isn't possible also to flash that file because i think don't work with f2fs partition.

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by VampireHeart** [comment]
Great work, thanks a lot.

**Pull request merged**
