### PR TITLE
Add support for Lava Pixelv1

### PR DESCRIPTION
**Pull request by MSF-Jarvis**
Shout out to @Anik1199 for adding support for Google Android One devices

~~Need instructions on how to test my patch. Should work well enough though, it's almost identical to the first generation devices internally.~~

Tried compiling locally, CMake was one  hell of a bitch. I'll let you guys run me a test build.

### CODE REVIEW

**Comment by MSF-Jarvis** [comment]
@Nonta72 I hope it's fine now

**Comment by Nonta72** [comment]
Hahahhh I guess so :+1:

**Comment by MSF-Jarvis** [comment]
Tested working. @chenxiaolong, you can merge it now. Cheers to @Nonta72 for the test build.

**Comment by Nonta72** [comment]
Please @chenxiaolong , please take a look at my pull request too.
I have fixed (I think) the conflict related to device ID.

Thanks.

**Comment by wazeeahmed** [comment]
@MSF-Jarvis bro have you tried extsd option yet ?

**Comment by MSF-Jarvis** [comment]
Should I ? data slot and system are working for me

**Comment by wazeeahmed** [comment]
Please test it . I tested with DU 10.5 resurrection remix 5.7.3 xosp 6.3 but none of them worked . It doesn't boot and can't flash gapps either . One more weird thing , can't dual boot with cm13 . whenever I boot into cm13 and then switch to the 2nd rom ; it doesn't boot . Just gets stuck at boot animation . Reason unknown yet .

**Comment by MSF-Jarvis** [comment]
I see no point in using extsd, but I will try if I have the space on my card. I have dual booted RR, stock ROM, and DU 10.4 with DU 10.5 as my primary ROM, both on a data slot and in the system partition itself with no issues.

**Comment by wazeeahmed** [comment]
You mean three roms at once ?  thats triple boot bro . Anyways please test with or without gapps . And can you please diagnose my issues ? I used twrp and inapp flashing but none helped .

**Comment by MSF-Jarvis** [comment]
Yeah I can do three ROMs yes, if you're flashing two ROMs and two GApps on a 1.5 gigabyte system partition, you're going to have GApps flashing failure on the second ROM, you can't change that in any easy way

**Comment by MSF-Jarvis** [comment]
Are you sure you even have the Lava Pixelv1? I am only supporting
that,first generation devices are Anik's responsibility

**Comment by wazeeahmed** [comment]
I know . He doesn't work on 1st generation anymore . He's now focused on xiaomi redmi 3 . That is why I had to report an issue here regarding extsd flashing . Because as it is mtk chipset , i guess you verify if it works on sd card or not . Though sd card detection was fixed few days ago . But something is bother in the flashing and booting process . Can't figure out which one .

**Comment by MSF-Jarvis** [comment]
I will not accept any bug reports for devices I don't support, sorry for
that.

**Comment by Anik1199** [comment]
@MSF-Jarvis i won't recommend to support sdcard on main branch. This patch can be used personally. Booting from SD is kinda risky.

**Comment by MSF-Jarvis** [comment]
I don't use the SDcard booting feature and have told all my testers to stay
away from it simply because we have ample spaces in our system and data
partitions for it. DarkHeart Z is talking about your patch which enabled
support for the first generation devices, mine is mint.

**Comment by wazeeahmed** [comment]
Or more clearly , It's kinda useless because can't flash gapps in the systwm while it's in the image format only . Data partition is the only hope here . seedmtk has bigger internal storage . So they're lucky to try three roms at once . I thought sd will let us try that too . Anyways I'm leaving the hope of trying rom installation on sd card . It seems only multirom users can be lucky to try that . Maybe better luck next time with one plus 3 for me when I'll have one .

**Comment by Caio99BR** [comment]
@chenxiaolong why not add to Milestone 9?

**Comment by chenxiaolong** [comment]
This has been committed to the `9.0.0-staging` branch: c1779f3131e724563b8acbaec14ea2ac5c926e1f

**Pull request closed without merging**
