### PR TITLE
 Please add my device n7100 note2 t03g

### PR DESCRIPTION
**Pull request by egoiste87**
Please add my device n7100

### CODE REVIEW

**Comment by egoiste87** [comment]
If something is wrong, I'm sorry, I'm from Russia it's difficult to understand very well

**Comment by egoiste87** [comment]
name: Samsung Galaxy Note 2		
 -  id: t03g		
 -  codenames:		
 -    - t03g				
 -  architecture: armeabi-v7a		
 -		
 -  block_devs:		
 -    base_dirs:		
 -      - /dev/block/platform/dw_mmc/by-name		
 -    system:		
 -      - /dev/block/platform/dw_mmc/by-name/SYSTEM		
 -      - /dev/block/mmcblk0p13		
 -    cache:		
 -      - /dev/block/platform/dw_mmc/by-name/CACHE		
 -      - /dev/block/mmcblk0p12		
 -    data:		
 -      - /dev/block/platform/dw_mmc/by-name/USERDATA		
 -      - /dev/block/mmcblk0p16		
 -    boot:		
 -      - /dev/block/platform/dw_mmc/by-name/BOOT		
 -      - /dev/block/mmcblk0p8		
 -    recovery:		
 -      - /dev/block/platform/dw_mmc/by-name/RECOVERY		
 -      - /dev/block/mmcblk0p9		
 -    extra:		
 -      - /dev/block/platform/dw_mmc/by-name/RADIO

**Comment by 911N-X** [comment]
You removed all the Note 3, Note 4 and 5 versions just to add Note 2?? chenxiaolong won't approve this change. You only have to add the different codename or just add your Note 2 as separated version.

**Comment by egoiste87** [comment]
Help please add my devices. I'm from the Russian hard to navigate github

**Comment by egoiste87** [comment]
To tears this program is needed

**Comment by maksorenru** [comment]
[20170417.010325.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/925343/20170417.010325.tar.gz)

**Comment by egoiste87** [comment]
For the second month, please add my device to xda. My device does not want to chenxiaolong ignore. I'm just waiting like an idiot. ((((

**Pull request closed without merging**
