### PR TITLE
Add support for combined boot/recovery partitions

### PR DESCRIPTION
**Pull request by chenxiaolong**

### CODE REVIEW

**Comment by Caio99BR** [comment]
https://gist.github.com/Caio99BR/84fce44b91c4e9951efb82e3d1493651

In ramdisk update it do "Creating Android boot image" 2 times
It now change default.prop and other ramdisk things, but not patch the fucking init.sh :(

**Comment by Caio99BR** [comment]
Also it break my Sony Home Screen

**Comment by chenxiaolong** [comment]
It's good that `init.sh` is not being patched :) It's now patching `/init` inside of `/sbin/ramdisk.cpio`. So when `init.sh` extracts that file, `/init` is created properly.

**Comment by Caio99BR** [comment]
> It's good that init.sh is not being patched :) It's now patching /init inside of /sbin/ramdisk.cpio. So when init.sh extracts that file, /init is created properly.

It look a lot more good, but my home screen is broken and ... i cant start DualBootPatcher app :/

**Comment by chenxiaolong** [comment]
> It look a lot more good, but my home screen is broken and ... i cant start DualBootPatcher app :/

Crap, that's bad... Does logcat still work?

**Comment by Caio99BR** [comment]
Yup, but the shit ROM of Sony is spamming it

Also in "Apps" > "Downloaded" show "No apps"

**Comment by Caio99BR** [comment]
https://gist.github.com/Caio99BR/ee881585703f1d88f0796108aa9b9036

**Comment by chenxiaolong** [comment]
> Yup, but the shit ROM of Sony is spamming it

Can I take a look at the full logcat (even if it is shit :P)?

**Comment by Caio99BR** [comment]
caio@c9:~/Downloads$ adb reboot; adb wait-for-device; adb logcat | tee log.txt
https://gist.github.com/Caio99BR/0c23573439bed6e424e197f9a07509a8

After adb connection close/open
caio@c9:~/Downloads$ adb logcat | tee log.txt
https://gist.github.com/Caio99BR/bb523af5bc6c332b2fdbff54f7ef3435

**Comment by chenxiaolong** [comment]
Looks like an SELinux issue:

```
E/PackageManager( 1062): Unable to copy native libraries
E/PackageManager( 1062): java.io.IOException: Cannot set SELinux context for /data/app-lib/asd.vector.sensor-1
E/PackageManager( 1062): 	at com.android.server.pm.PackageManagerService.copyNativeLibrariesForInternalApp(PackageManagerService.java:5496)
E/PackageManager( 1062): 	at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:4945)
E/PackageManager( 1062): 	at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:4049)
E/PackageManager( 1062): 	at com.android.server.pm.PackageManagerService.scanDirLI(PackageManagerService.java:3766)
E/PackageManager( 1062): 	at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:1539)
E/PackageManager( 1062): 	at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:1108)
E/PackageManager( 1062): 	at com.android.server.ServerThread.initAndLoop(SystemServer.java:281)
E/PackageManager( 1062): 	at com.android.server.SystemServer.main(SystemServer.java:1289)
E/PackageManager( 1062): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/PackageManager( 1062): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/PackageManager( 1062): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:814)
E/PackageManager( 1062): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)
E/PackageManager( 1062): 	at dalvik.system.NativeStart.main(Native Method)
```

The app sharing code can definitely cause something like this. If you flash the original `/sdcard/MultiBoot/[ROM ID]/boot.img.before-ramdisk-update.img`, does everything work again? If yes, I'll make a build with app sharing removed for you to test.

**Comment by Caio99BR** [comment]
>The app sharing code can definitely cause something like this. If you flash the original /sdcard/MultiBoot/[ROM ID]/boot.img.before-ramdisk-update.img, does everything work again? If yes, I'll make a build with app sharing removed for you to test.

Yes, all is working again now

**Comment by chenxiaolong** [comment]
@Caio99BR OK, that's good. Can you try this build? https://jenkins.noobdev.io/job/DualBootPatcher_Build/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/202/

It's exactly the same as this PR, except it also removes app sharing support.

**Comment by Caio99BR** [comment]
Let's go!
Downloading...

**Comment by Caio99BR** [comment]
This still not working

**Comment by Caio99BR** [comment]
I will check it on CM11

**Comment by chenxiaolong** [comment]
Ok, I just saw this from the logs before:

```
E/SELinux ( 1062): file_context_open: Error getting file context handle (Permission denied)
```

So it cannot read `/file_contexts`. Can you post the output of `ls -lZ /file_contexts`?

**Comment by Caio99BR** [comment]
Before patching:
>root@D2114:/ # ls -lZ /file_contexts
-rw-r----- system   system            u:object_r:rootfs:s0 file_contexts

After patching (just switched to patched img):
root@D2114:/ # ls -lZ /file_contexts
-rw-r----- root     root              u:object_r:rootfs:s0 file_contexts

**Comment by Caio99BR** [comment]
It really is simple and bad XD

**Comment by Caio99BR** [comment]
https://www.diffchecker.com/xMw8niWt

**Comment by chenxiaolong** [comment]
> https://www.diffchecker.com/xMw8niWt

Nice find! That would definitely cause problems. And it's an easy fix too.

**Comment by chenxiaolong** [comment]
@Caio99BR New build incoming :) https://jenkins.noobdev.io/job/DualBootPatcher_Build/203/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/

**Comment by Caio99BR** [comment]
Now it's fine!
Can you add BootUI, please :P 
graphics_backends is fbdev, flag used is TW_GRAPHICS_FORCE_USE_LINELENGTH, pixel_format is RGBX_8888, cpu_temp_path i not defined on TWRP but it is showed, theme is portrait_hdpi
And i used this patch: <https://gerrit.omnirom.org/#/c/18815/>

If no, thanks a lot! :D 

NOTE: Also check bootui on primary
NOTE2: I have look at that EDIT in begin now :P, i have extracted it before you say

**Comment by chenxiaolong** [comment]
> Now it's fine!

Awesome, great :P

> Can you add BootUI, please :P 
> graphics_backends is fbdev, flag used is TW_GRAPHICS_FORCE_USE_LINELENGTH, pixel_format is RGBX_8888, cpu_temp_path i not defined on TWRP but it is showed, theme is portrait_hdpi

Sure, which device should I add it for? honami?

> And i used this patch: https://gerrit.omnirom.org/#/c/18815/

Not necessary because overlay graphics will not be used unless it is explicitly listed in the device yml file.

**Comment by Caio99BR** [comment]
> Sure, which device should I add it for? honami?

Add for... ALL 3 :P 
I think the fbdev is like default and work on all
If not my device is falconss :)

**Comment by chenxiaolong** [comment]
I don't know what device armani is, but I added it for falconss, honami, and tianchi :)

**Comment by Caio99BR** [comment]
> I don't know what device armani is, but I added it for falconss, honami, and tianchi :)

XD, ok armani not exist (maybe yet :P)

Now you can close:
https://github.com/chenxiaolong/DualBootPatcher/issues/8

OOOPS, we forget this device:
https://github.com/chenxiaolong/DualBootPatcher/pull/74

And also by last, and less important (why not add in Milestone 9?):
https://github.com/chenxiaolong/DualBootPatcher/issues/93

I will test it now :+1:

**Comment by chenxiaolong** [comment]
> Now you can close:
> https://github.com/chenxiaolong/DualBootPatcher/issues/8

Done!

> OOOPS, we forget this device:
> https://github.com/chenxiaolong/DualBootPatcher/pull/74
>
> And also by last, and less important (why not add in Milestone 9?):
> https://github.com/chenxiaolong/DualBootPatcher/issues/93

I'll add both of these tomorrow. Should be easy enough :)

**Comment by Caio99BR** [comment]
Only reporting, i have tested it on Xperia T2 Ultra and app just crash, without reason, when i go to ROMs it just crash, no log, and no logcat until end of week. Idk if is because recovery is missing (Pure Sony Stock ROM 5.1), but is only it.
I will open a issue when i get logcat and try some things :+1:

**Pull request merged**
