### PR TITLE
Add BootUI for Oneplus One

### PR DESCRIPTION
**Pull request by chenxiaolong**
BootUI support for Oneplus One

### CODE REVIEW

**Comment by chenxiaolong** [comment]
Test build at https://jenkins.noobdev.io/job/DualBootPatcher_Build/214/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/

**Comment by ab123321** [comment]
Yeah, it works!

**Comment by chenxiaolong** [comment]
@ab123321 Thanks for testing!

**Comment by ab123321** [comment]
@chenxiaolong the only sad thing is that my primary system became broken (before ending of bootanimation device reboots, there is no errors/fatals in logcat). Also, my /data/media/0/ folder was moved to /data/media/0/0/0/0/. All secondary ROMs work normally.

**Pull request merged**
