### PR TITLE
libmbp: Add support for vee3 (LG L3 II) and m4 (LG L5)

### PR DESCRIPTION
**Pull request by Caio99BR**

### CODE REVIEW

**Comment by Caio99BR** [comment]
@chenxiaolong any way to merge? btw tested

**Comment by chenxiaolong** [comment]
Merged, thank you! (And thanks for adapting your old PR for the changes from yesterday).

**Comment by Caio99BR** [comment]
Ok but is me need to say thanks :P

**Comment by Caio99BR** [comment]
Maybe after i add support to one more LG device.

**Pull request merged**
