### PR TITLE
Initial attempt at klte Boot UI support

### PR DESCRIPTION
**Pull request by chenxiaolong**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
Test build is available here: https://jenkins.noobdev.io/job/DualBootPatcher_Build/139/target=android-all-gcc/

**Comment by Caio99BR** [comment]
@chenxiaolong why not add to Milestone 9?

**Comment by IncognitoJam** [comment]
The test build has since disappeared from Jenkins. Could it possibly be re-built and I would test it on my own device?
Thanks, and great work! (I remember contacting you about this a while ago :smile:)

**Comment by chenxiaolong** [comment]
@IncognitoJam Sure, the new test build is available here :smile: https://jenkins.noobdev.io/job/DualBootPatcher_Build/212/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/

**Comment by chenxiaolong** [comment]
Test build: https://jenkins.noobdev.io/job/DualBootPatcher_Build/314/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/

**Pull request merged**
