### PR TITLE
Update lenovo.yml

### PR DESCRIPTION
**Pull request by yuraas**

### CODE REVIEW

**Comment by dg28gadhavi** [comment]
Sorry to say but this is not the correct way to request for a a device support:(

To PR 1st know your device partition blocks u can use diskinfo app to know the same if u don't have much idea (I.e system=mmcblk20) 

Then peep in /dev folder of your device root and set correct paths of base directory and all

Collect your device codenames (I.e our k4 has A7010a48,Vibe X3 lite... etc)

Then Define values and various flags like bootui is supported or not,default brightness and all 

Read sample.yml for that you will learn more

Or simply the best idea would be download getlogs.zip and give the logs to dev;)

**Comment by yuraas** [comment]
4 трав. 2017 18:58 "DHRUV GADHAVI" <notifications@github.com> пише:

Sorry to say but this is not the correct way to request for a a device
support:(

To PR 1st know your device partition blocks u can use diskinfo app to know
the same if u don't have much idea (I.e system=mmcblk20)

Then peep in /dev folder of your device root and set correct paths of base
directory and all

Collect your device codenames (I.e our k4 has A7010a48,Vibe X3 lite... etc)

Then Define values and various flags like bootui is supported or
not,default brightness and all

Read sample.yml for that you will learn more

Or simply the best idea would be download getlogs.zip and give the logs to
dev;)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chenxiaolong/DualBootPatcher/pull/550#issuecomment-299229658>,
or mute the thread

**Comment by dg28gadhavi** [comment]
@yuraas if You have pc and sdk platform tools install (adb) i can help u to PR:) 

Go in pc connect your phone in usb debugging mode and connect to adb in pc

Type following commands in adb shell

1. adb devices
2. adb shell (grant superuser rights in your phone by this command)
3. cat /proc/emmc
         
            OR

cat /proc/mtd


And share me the output here;)

**Comment by dg28gadhavi** [comment]
@yuraas or simply download terminal emulator and grant it superuser rights

And type following commands

su

ls /dev/block/platform/msm_sdcc.1/by-name


And share the output here ;)

**Comment by yuraas** [comment]
5 трав. 2017 06:42 "DHRUV GADHAVI" <notifications@github.com> пише:

**Comment by dg28gadhavi** [comment]
@yuraas i am not getting your language are  you going to share output of the comands said????

**Comment by dg28gadhavi** [comment]
@yuraas firstly close this PR

**Comment by yuraas** [comment]
5 трав. 2017 08:09 "DHRUV GADHAVI" <notifications@github.com> пише:

**Pull request closed without merging**
