### PR TITLE
data: Add Boot UI support for sprout

### PR DESCRIPTION
**Pull request by chenxiaolong**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
Test build: https://jenkins.noobdev.io/job/DualBootPatcher_Build/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/221/

**Comment by wazeeahmed** [comment]
Sorry for the silly question . But how do I use the boot ui ? Do I have to patch the recovery in order to do that ?

**Comment by hankching** [comment]
Settings -≥ Install Boot UI

You didn't carefully read message showed to you.

Update ramdisk (all individually) must be done, otherwise it will never show Boot UI.

**Comment by wazeeahmed** [comment]
@chenxiaolong please take a look at issue #200 . I think the ramdisk update option really needs to be taken care of .

**Comment by wazeeahmed** [comment]
already figured it out . But the ramdisk update option is buggy in my device . I opened an issue #176 referring this . Even a new one #200 just because now it's connected .

**Comment by wazeeahmed** [comment]
It seems I have to find the hasselful way this time to fix it .

**Comment by wazeeahmed** [comment]
I tried . And the result was : 

1. device hanged up in boot logo and vibrated twice .
2. Directly booted into recovery mode .

Here are the log : 
[20160919.031558.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/478996/20160919.031558.tar.gz)

**Comment by chenxiaolong** [comment]
@wazeeahmed The failure is unrelated to the Boot UI. The ramdisk is missing the `/romid` file. How did you flash your current kernel?

**Comment by wazeeahmed** [comment]
Got it . My fault . This time I'll do full flash . I only flashed kernel before . Bro please can you fix the ramdisk update option ? #200 As you can see . My data partition is eaten up mostly by secondary rom and primary rom's files . I got space errors when trying to reflash stock rom .

**Comment by wazeeahmed** [comment]
@chenxiaolong I got this working . Some little bugs are still there .
1. custom cpu temparature fix in bootui :  /sys/devices/virtual/thermal/thermal_zone1/temp
2 . couldn't switch roms 😥 . Whenever I press switch roms it instantly boots into rom I selected from dbp app .

**Comment by chenxiaolong** [comment]
Thanks for the info!

> @chenxiaolong I got this working . Some little bugs are still there .
> 1. custom cpu temparature fix in bootui :  /sys/devices/virtual/thermal/thermal_zone1/temp

Done. New test build: https://jenkins.noobdev.io/job/DualBootPatcher_Build/225/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/

> 2 . couldn't switch roms 😥 . Whenever I press switch roms it instantly boots into rom I selected from dbp app .
Here's the exec log : 
[exec.log.zip](https://github.com/chenxiaolong/DualBootPatcher/files/482226/exec.log.zip)

This is a known bug. I have a pretty good idea why it's happening and will fix it soon.

> One more major bug .
> (...)
> Primary rom have everything . But secondary rom /cache is just like it was in the factory mode . 

This is normal. Only one copy of the Boot UI at the "real" cache partition path is needed. (ie. `/cache` when booted to the primary ROM, `/raw/cache` when booted to any other ROM)

> Bootui settings always needs to be reconfigured ; everytime system boots .

This is probably caused by the Switch ROM function crashing. The TWRP/Boot UI settings code is designed so that the settings are saved if it exits normally. When it crashes, nothing is saved (so nothing will be corrupted).

**Comment by wazeeahmed** [comment]
Bro one more thing I should let you know . I can't flash roms on sd card from recovery . It always ends in error . Can you please check on the recovery and see why flashing error is occuring ?

**Comment by wazeeahmed** [comment]
Here's the logs of my flash to extsd : 
[MultiBoot.log.zip](https://github.com/chenxiaolong/DualBootPatcher/files/483936/MultiBoot.log.zip)
[recovery.log.zip](https://github.com/chenxiaolong/DualBootPatcher/files/483937/recovery.log.zip)

**Comment by chenxiaolong** [comment]
> Bro one more thing I should let you know . I can't flash roms on sd card from recovery . It always ends in error . Can you please check on the recovery and see why flashing error is occuring ?

> @chenxiaolong Here's the logs of my flash to extsd : 
[MultiBoot.log.zip](https://github.com/chenxiaolong/DualBootPatcher/files/483936/MultiBoot.log.zip)
[recovery.log.zip](https://github.com/chenxiaolong/DualBootPatcher/files/483937/recovery.log.zip)

It happened because TWRP mounted the external SD at `/microSD`, which was not recognized by the patcher. This should be fixed now. New test build: https://jenkins.noobdev.io/job/DualBootPatcher_Build/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/228/

**Comment by chenxiaolong** [comment]
@wazeeahmed The Boot UI crashing bug is fixed by #205. A new test build is available here: https://jenkins.noobdev.io/job/DualBootPatcher_Build/230/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/

**Comment by wazeeahmed** [comment]
You're a genie bro . Two fix at a time . Just magical 😀 . Testing right now and letting you know . 😊

**Comment by wazeeahmed** [comment]
@chenxiaolong Confirmed working . All is good now . Please merge it  . 😊

**Pull request merged**
