### PR TITLE
Add support for SM-G530H/FZ/M

### PR DESCRIPTION
**Pull request by faizauthar12**

### CODE REVIEW

**Comment by faizauthar12** [comment]
@chenxiaolong please :)

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
@faizauthar12 Test builds are available here: https://jenkins.noobdev.io/job/DualBootPatcher_Build/618/label_exp=dualbootpatcher-builder,target=android-all-gcc/

**Comment by faizauthar12** [comment]
works!
thank you @chenxiaolong

**Comment by chenxiaolong** [comment]
Great! Merged

**Comment by chenxiaolong** [comment]
Original comment in OP (removed to prevent it from showing in merge commit):

> Hello ( again )
> i already defined a correct partition, but i can't make an apk...
> can you make a test build for this PR?
> thanks before
>
> oh ya, this is what i face...
> i am using the latest SDK ..
> ```
> FAILURE: Build failed with an exception.
>
> * What went wrong:
> A problem occurred configuring root project 'Android_GUI'.
> > Failed to find target with hash string 'android-25' in: /home/faizauthar/android/android-sdk
>
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
>
> BUILD FAILED
>
> Total time: 0.879 secs
> Android_GUI/CMakeFiles/apk.dir/build.make:57: recipe for target 'Android_GUI/CMakeFiles/apk' failed
> make[3]: *** [Android_GUI/CMakeFiles/apk] Error 1
> CMakeFiles/Makefile2:727: recipe for target 'Android_GUI/CMakeFiles/apk.dir/all' failed
> make[2]: *** [Android_GUI/CMakeFiles/apk.dir/all] Error 2
> CMakeFiles/Makefile2:734: recipe for target 'Android_GUI/CMakeFiles/apk.dir/rule' failed
> make[1]: *** [Android_GUI/CMakeFiles/apk.dir/rule] Error 2
> Makefile:301: recipe for target 'apk' failed
> make: *** [apk] Error 2
> ```

**Pull request merged**
