### PR TITLE
Move device definitions from libmbp to YAML files

### PR DESCRIPTION
**Pull request by chenxiaolong**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by hankching** [comment]
Everything is fine for jiayu s3.

Unrelated bugs as follows:
1. Built-in flash can't update boot partition for Android M (6.0.1) but switch rom function is OK.
2. Update ramdisk missing create ro.patcher.device and ro.patcher.use_fuse_extsd when default.prop without them.

Suggestions
1. Put romid, ro.patcher.device and ro.patcher.use_fuse_extsd into device.json
2. Add extsd_dir into device.json and find "/devices/mtk-msdc.0/11240000.MSDC1*" instead of "voldmanaged=sdcard1".
3. Add target _system_path, target _data_path and target _cach_path into device.json

**Comment by chenxiaolong** [comment]
@hankching Thanks for testing and confirming that it works! Regarding your points:

> 1. Built-in flash can't update boot partition for Android M (6.0.1) but switch rom function is OK.

Can you post `/sdcard/MultiBoot/daemon.log` after trying to update the boot partition?

> 2. Update ramdisk missing create ro.patcher.device and ro.patcher.use_fuse_extsd when default.prop without them.

Yes, the missing `ro.patcher.device` property is definitely a bug. However, `ro.patcher.use_fuse_exfat` should always be added during the ramdisk update unless `/system/bin/vold` cannot be read. Can you post `/sdcard/MultiBoot/ramdisk-update.log`?

> Suggestions
> 1. Put romid, ro.patcher.device and ro.patcher.use_fuse_extsd into device.json

These cannot be set in `device.json` by the maintainer for many devices. Samsung devices, in particular, can use fuse-exfat or the kernel exfat driver depending on the ROM. Thus, it cannot be a fixed value.

> 2. Add extsd_dir into device.json, YAML file and find "/devices/mtk-msdc.0/11240000.MSDC1*" instead of "voldmanaged=sdcard0, voldmanaged=sdcard1, .....".

This must be determined from the fstab file because mbtool must mount the SD card with the exact same options as Android. Otherwise, Android won't detect the SD card. But maybe the `voldmanaged=` value can go in devices.json.

> 3. Add target _system_path, target _data_path and target _cach_path into device.json

Why would this be necessary? These values are automatically determined based on the ROM ID.

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by wazeeahmed** [comment]
@chenxiaolong unable to boot from sd card months ago , can't flash gapps on rom installed on sd card . I had opened an issue on that and attached logs too . But nobody replied on that . Waited for weeks . issue number #148 . Though I closed it 1 week ago .

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by hankching** [comment]
@chenxiaolong 

1 Built-in flash only create MultiBoot.log file. Attached as below.
2 Update ramdisk isn't current ROM, maybe it misses ro.patcher.use_fuse_exfat too.
3 extsd_dir, I understood now.
4 device.json file from boot.img, I think everything should put together, therefore I suggest delete romid file from boot.img and don't modify default.prop file too. My idea is relocation.
5 target _path for system, data and cach. Using these can reduce code (I think) and user can change where they want to put. My idea is that before patch zip file, user selects path, size and image type ( folder or file) and then update device.json inside zip file first. Booting stage, check path exist or not, after booting process (execlp /init).

[MultiBoot_fail.log.txt](https://github.com/chenxiaolong/DualBootPatcher/files/440985/MultiBoot_fail.log.txt)

**Comment by chenxiaolong** [comment]
> 1 Built-in flash only create MultiBoot.log file. Attached as below.

Thanks for the log. I think I found the issue. Can you open a new issue for this?

> 2 Update ramdisk isn't current ROM, maybe it misses ro.patcher.use_fuse_exfat too.

Ah yes, you're correct. This is only done when updating the ramdisk for the current ROM.

> 4 device.json file from boot.img, I think everything should put together, therefore I suggest delete romid file from boot.img and don't modify default.prop file too. My idea is relocation.

I will take this into consideration.

> 5 target _path for system, data and cach. Using these can reduce code (I think) and user can change where they want to put. My idea is that before patch zip file, user selects path, size and image type ( folder or file) and then update device.json inside zip file first. Booting stage, check path exist or not, after booting process (execlp /init).

I plan to implement this a little differently in the future. I'd like to have a folder, such as `/sdcard/MultiBoot/rom-slots`, where the user can create a slot of his/her choice. Any custom slots here will show up in the app and can be used when flashing the patched ROM.

**Pull request merged**
