### PR TITLE
mbtool: Remount partitions as writable before restoring a backup (fixes #535)

### LINKED ISSUE #535: mbtool does not remount /system as writable before restoring backup

### PR DESCRIPTION
**Pull request by chenxiaolong**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
Test build: https://jenkins.noobdev.io/job/DualBootPatcher_Build/727/label_exp=dualbootpatcher-builder,target=android-all-gcc/

**Comment by Caio99BR** [comment]
Tested and worked!
+1 to merge :)

---

PS0: Thanks for solve this issue :)
PS1: The checksum is not updated with ROM Restore.
PS2: If Secondary ROM is same of Primary, when you're at Secondary ROM the ROMs screen will show Primary as selected but Secondary is set.

**Comment by chenxiaolong** [comment]
Great!

---
> PS1: The checksum is not updated with ROM Restore.
> PS2: If Secondary ROM is same of Primary, when you're at Secondary ROM the ROMs screen will show Primary as selected but Secondary is set.

Can you open new issues for these? I can take a look tomorrow.

The first one should be pretty easy to fix. For the second one, the app opens the boot partition and reads `/romid`. If that file doesn't exist, then it assumes the ROM is primary (ie. ROM without updated ramdisk). Maybe it's having trouble reading that file.

**Comment by Caio99BR** [comment]
Ok :+1:

**Comment by Caio99BR** [comment]
I think you should delete `fix-issue-533` and `patch-ramdisk-during-install` they are in `master`, no?
`kmsg-force-error` is not need anymore.
Also merge `homtom-support`, `htc-pme-support` and `land-support`, just saying it to make project clean :P

After 'clean' only these branch (from 10 to 3): `master`, `libmbdevice-c++` and `drop-appsync`

**Comment by chenxiaolong** [comment]
All done! I deleted the `*-support` branches since nobody tested those PRs.

**Comment by Caio99BR** [comment]
Oh :(

**Pull request merged**
