### PR TITLE
Add Indonesian Translation for DualBoot App

### PR DESCRIPTION
**Pull request by RieTech**
Trying. . .

### CODE REVIEW

**Comment by faizauthar12** [comment]
@RieTech in is for india
ina is for indonesia

correct it please :)

**Comment by RieTech** [comment]
After android get Nougat, Indonesian string become values-ina? So funny, how do u know it? any article or something post about it?

**Comment by faizauthar12** [comment]
Hmm,well i never check string 
I just know that in for india and ina for indonesia

**Comment by chenxiaolong** [comment]
If the translations here are still accurate, please upload them at Transifex: https://www.transifex.com/dualbootpatcher/dualbootpatcher/

I can't merge translation PRs without affecting the current Transifex setup.

Thanks!

**Pull request closed without merging**
