### PR TITLE
Mi5S boot UI support

### PR DESCRIPTION
**Pull request by v1ack**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by kbootroza** [comment]
Please create boot ui support mi5s

**Comment by yshalsager** [comment]
@kbootroza it's added by me 
https://github.com/chenxiaolong/DualBootPatcher/commit/44dbcc720569eef6f04b995ade4fe09000592934#diff-1e99ca5a6c10c5c75af99fe1c92687c2R289

**Comment by chenxiaolong** [comment]
Closing this PR since support has been added already.

**Pull request closed without merging**
