### PR TITLE
Sony: Rebased from PR #76 (Combined patch boot/recovery ramdisk)

### PR DESCRIPTION
**Pull request by Caio99BR**
We need to get a way to deal with mounts inside *.rc files
Rebase of #76

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by Caio99BR** [comment]
https://gist.github.com/Caio99BR/0f5ade6b91ae962e19578c90f3ee64dc

I will patch CM11 and try again, tomorrow

**Comment by Caio99BR** [comment]
[    5.189128] mblog: fstab file: /fstab.qcom
[    5.189758] mblog: Unknown ROM ID: 
[    6.339521] elan_ktf2k_ts_check_work_func, chip may crash, we need to reset it 
[    6.443059] mblog: --- EMERGENCY REBOOT FROM MBTOOL ---
[    6.444540] mblog: /data is not mounted. Attempting to mount /data
[    6.445491] mblog: Dumping kernel log to /data/media/0/MultiBoot/kernel.log
[    6.472490] mblog: /data/media/0/MultiBoot: Failed to set context to unlabeled: Success

----

In my patched kernel (FalconSSKernel R5r8), extracted boot.img, put on original package, flashed, wait to normal boot. crash and reboot to recovery, this is from last_kmsg, the kernel.log not exist
The ramdisk update not work.
I will flash CM11 on Secondary and test, since Xperia E1 is my new phone :)

**Comment by chenxiaolong** [comment]
> `[ 5.189758] mblog: Unknown ROM ID: `

Hmm, that's a problem. It determines the ROM ID by reading the `/romid` file in the ramdisk.

**Comment by Caio99BR** [comment]
Another last_kmsg from CM11: https://gist.github.com/Caio99BR/851297e56217e88b949fca14811b88f1

**Comment by Caio99BR** [comment]
> Hmm, that's a problem. It determines the ROM ID by reading the /romid file in the ramdisk.
Maybe on stock

Here kernel.log from CM11: https://gist.github.com/Caio99BR/92e74ed6dea3e596a23ad52ab06e6b4b

**Comment by chenxiaolong** [comment]
CM11 seems to work properly until the last step: It can't find `/init`.

**Comment by Caio99BR** [comment]
Any way to build with this latest change?

**Comment by Caio99BR** [comment]
I have added mbtool direct on my edited ramdisk and now

https://gist.github.com/Caio99BR/9438f5f262fdeaa3d84aa7317fecdf7a

**Comment by Caio99BR** [comment]
It wont patch the default.prop inside of /sbin/ramdisk.cpio :/

**Comment by Caio99BR** [comment]
Bump
Any way to check it?

**Comment by Caio99BR** [comment]
REBUMP, @chenxiaolong can you check it, please

**Comment by chenxiaolong** [comment]
@Caio99BR I'm working on it now. I've simplified the implementation a bit and will open a new PR soon :)

**Comment by Caio99BR** [comment]
Thanks, sorry for spam/flood :P
Closing pull request

**Comment by Caio99BR** [comment]
@chenxiaolong you need a seriously cleanup on your branchs :+1:

**Comment by chenxiaolong** [comment]
@Caio99BR The new PR has been created #174

> @chenxiaolong you need a seriously cleanup on your branchs 👍

Oh wow... yeah... that's quite a bit. They're cleaned up now :)

**Comment by Caio99BR** [comment]
Ok, downloading for test

> Oh wow... yeah... that's quite a bit. They're cleaned up now :)
I think you already said, "this guy is too inconvenient"

**Pull request closed without merging**
