### PR TITLE
Add support for Lenovo A536

### PR DESCRIPTION
**Pull request by stydent21rus**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@noobdev-bot test this please

**Comment by chenxiaolong** [comment]
@noobdev-bot test this please

**Comment by chenxiaolong** [comment]
@noobdev-bot retest this please

**Comment by chenxiaolong** [comment]
@noobdev-bot test this please

**Comment by chenxiaolong** [comment]
@stydent21rus I had to remove the eMMC paths because DualBootPatcher doesn't support them. Please give the test build here a try: https://jenkins.noobdev.io/job/DualBootPatcher_Build/629/

**Comment by stydent21rus** [comment]
Hello!!!I understand that the problems due to kernel and recovery???

**Comment by stydent21rus** [comment]
https://github.com/stydent21rus/ST-Team-/blob/master/ramdisk-update.log

**Comment by stydent21rus** [comment]
https://github.com/stydent21rus/ST-Team-/blob/master/boot-ui-action.log

**Comment by stydent21rus** [comment]
Logs attached!!!!

**Comment by chenxiaolong** [comment]
Closing due to merge conflicts and invalid paths (`/by-num/` instead of `/by-name/`).

**Pull request closed without merging**
