### PR TITLE
Add HTC one M8 support

### PR DESCRIPTION
**Pull request by atxoxx**
Add HTC one M8 support

### CODE REVIEW

**Comment by atxoxx** [comment]
Chenxiaolong is it possible to review this ?

**Comment by TheComputerGuy96** [comment]
@atxoxx Please use Unix newlines and UTF-8 encoding

**Comment by atxoxx** [comment]
@TheComputerGuy96 DOne thanks for the tips :)

**Comment by atxoxx** [comment]
Forgot to change the file extension all done now

**Comment by navhaxs** [comment]
`HTC.yml` also needs to be added to `data/devices/CMakeLists.txt`

I tested this patch on my HTC M8, there is still further work needed. Codename should be 'htc_m8' (at least on my phone?)

Was this actually successfully tested on the HTC 10?

**Comment by atxoxx** [comment]
@navhaxs Hmm I think the codename depends on roms 
Sometimes its m8 sometimes its htc_m8 
Better to use both maybe 
The patch work tho ? 
I didn't managed to make a build

**Comment by navhaxs** [comment]
I get "Failed to update ramdisk" from the Android gui when trying "Update ramdisk" for the primary ROM. Did not test patching/flashing a ROM yet. So far I've only found the following debug messages, but more digging is required to understand the root cause as to why it is not working.

1. `/sdcard/MultiBoot/logs/ramdisk-update.log`
```
--------- beginning of main
06-23 23:59:40.104  3117  3154 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8226_LA.BF.1.1.3_RB1__release_AU (I741a3d36ca)
06-23 23:59:40.104  3117  3154 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.29.00.00
06-23 23:59:40.104  3117  3154 I Adreno-EGL: Build Date: 04/17/16 Sun
06-23 23:59:40.104  3117  3154 I Adreno-EGL: Local Branch: 
06-23 23:59:40.104  3117  3154 I Adreno-EGL: Remote Branch: quic/LA.BF.1.1.3_rb1.13
06-23 23:59:40.104  3117  3154 I Adreno-EGL: Local Patches: NONE
06-23 23:59:40.104  3117  3154 I Adreno-EGL: Reconstruct Branch: NOTHING
06-23 23:59:40.143  3117  3117 D SwitcherService: onCreate()
06-23 23:59:40.211  3117  3117 D SwitcherService: onBind(intent=Intent { cmp=com.github.chenxiaolong.dualbootpatcher.debug/com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherService })
06-23 23:59:40.231  3117  3117 D SwitcherService: onStartCommand(intent=Intent { cmp=com.github.chenxiaolong.dualbootpatcher.debug/com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherService }, flags=0, startId=1)
06-23 23:59:42.082  3117  3117 D SwitcherService: Added runnable com.github.chenxiaolong.dualbootpatcher.switcher.service.CreateRamdiskUpdaterTask@64725ed to thread pool: default
06-23 23:59:42.117  3117  3154 W OpenGLRenderer: Fail to change FontRenderer cache size, it already initialized
06-23 23:59:42.204  3117  5596 D CreateRamdiskUpdaterTask: Creating ramdisk updater zip for primary (version: 9.2.0-DEBUG)
06-23 23:59:42.935  3117  5596 I System  : exec(logcat -d -v threadtime -f /storage/emulated/0/MultiBoot/logs/ramdisk-update.log * @ com.github.chenxiaolong.dualbootpatcher.LogUtils.dump:43)
```

2. `Logcat` snippet: https://gist.github.com/navhaxs/6f8985597e444787df6e07183ef3f821 (how to filter for only relevant messages?)

**Comment by atxoxx** [comment]
I'll take a look when I have time 
If I have something you'll build the APK ?

**Comment by navhaxs** [comment]
@atxoxx yeah I can try build

**Comment by navhaxs** [comment]
Okay, it actually was working on M8!

After figuring out the flashing log was at `/sdcard/MultiBoot.log`, this revealed that the ramdisk was failing to patch only because the boot.img size was exceeded. After flashing ElementalX kernel, which was presumably smaller, the boot image could be successfully patched.

Test APK with my changes:
[Android_GUI-debug-HTC.zip](https://github.com/chenxiaolong/DualBootPatcher/files/1123221/Android_GUI-debug-HTC.zip)

@atxoxx if you add me to your repo I think I can push my changes, otherwise I can create a new PR.

Also, don't think anyone has tested HTC 10.

**Comment by atxoxx** [comment]
@navhaxs 
I'll add you ;) 

Thanks for the build 
Here is my telegram @I3lambda 
Or my mail sethezair@gmail.com

**Comment by navhaxs** [comment]
@chenxiaolong I think this is ready to merge.

**Comment by atxoxx** [comment]
Thanks @navhaxs ;)

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Pull request merged**
