### PR TITLE
Adding all the surnia CDMA variants (Moto E 2015)

### PR DESCRIPTION
**Pull request by f1vefour**
Please review and add if you can.

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@kostoulhs @kykdev @ModdingMyMind @zeeshanhussain @Caio99BR @onano @SerenityS @f1vefour Just a heads up, since all of you contributed (and therefore must have compiled the project at one point). The cmake build scripts for this project now requires `-DMBP_BUILD_TARGET=android` instead of `-DMBP_BUILD_ANDROID=true`. I've updated the docs with the new commands.

Also it is no longer necessary to manually dump the hex representation of the signing key's certificate. No more messing with `Android.certs.mk` or `validcerts.cpp` :)

**Comment by kykdev** [comment]
Got it, thanks :)

**Comment by zeeshanhussain** [comment]
woot Android.certs.mk always creates problem for me good to know its fixed :dancer:

**Comment by onano** [comment]
Thanks, for headsup

**Comment by f1vefour** [comment]
Thanks

**Comment by SerenityS** [comment]
Thanks.

**Comment by ModdingMyMind** [comment]
That's good to know. Thanks!

**Pull request merged**
