### PR TITLE
DualBootPatcher: Add Android One Devices

### PR DESCRIPTION
**Pull request by Anik1199**
Signed-off-by: Anik khan <anik9280@gmail.com>

### CODE REVIEW

**Comment by chenxiaolong** [comment]
Could you fix the indentation in the files? DualBootPatcher uses 4 spaces per indentation level. I'll merge after that. Thanks!

**Comment by Anik1199** [comment]
@chenxiaolong i hope now its fine :)

**Comment by chenxiaolong** [comment]
Merged, thank you :)

**Comment by Nonta72** [comment]
Hey
What about Infinix Hot 2 ? It's another version of Android One 2nd Gen but mnt points are slightly different from Android One 1st gen ones.
I can provide necessary info if needed.

**Comment by idamhcaoke** [comment]
i very need the new real link dualboot apk for sprout (androidone) thankz...

**Comment by Moalamir** [comment]
Hello All in my redmi note 3 pro kenzo when I install rom from app say this device is Kate

**Pull request merged**
