### PR TITLE
data: Add support for tomato

### PR DESCRIPTION
**Pull request by out386**
Commit's by Anand Shekhawat, I'm just giving the PR.

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please (this is a message for the build server)

**Comment by HyperloopX** [comment]
Test build works ! Please merge support for TOMATO ASAP!

**Comment by HyperloopX** [comment]
Please merge this asap for official builds.  Dualboot patcher and utilites work absolutely fine.

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Pull request merged**
