### PR TITLE
Add support for Nubia Z11 mini(nx529j)

### PR DESCRIPTION
**Pull request by sky0hjh**

### CODE REVIEW

**Comment by sky0hjh** [comment]
@chenxiaolong I can't build and test it for now.Can you build a test build to help me test with my Z11 mini? Thank you.

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
@sky0hjh A test build is available here: https://jenkins.noobdev.io/job/DualBootPatcher_Build/628/label_exp=dualbootpatcher-builder,target=android-all-gcc/

**Comment by sky0hjh** [comment]
@chenxiaolong Thanks.
MultiBoot feature is working, but I've found something wrong with fingerprint between the main OS and the
secondary OS.....

**Pull request merged**
