### PR TITLE
Add HOMTOM ZOJI Z7

### PR DESCRIPTION
**Pull request by t76**
Hi. Please add homtom zoji z7. Thank You.

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
The build failed because `/dev/block/mmcblk1p1` was listed twice. Can you please remove one of them?

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by t76** [comment]
Thank You very much!! It's working.

**Pull request merged**
