### PR TITLE
mbtool: init.cpp: Fix Boot UI skip file not being deleted after switching ROMs

### PR DESCRIPTION
**Pull request by chenxiaolong**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
Test build: https://jenkins.noobdev.io/job/DualBootPatcher_Build/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/217/

**Comment by hankching** [comment]
Confirmed that it works.

Pls merge it.

Thanks

**Comment by wazeeahmed** [comment]
@hankching Bro how to add bootui support ? Can you tell me in short if long description is not possible . would love to implement it .

**Comment by chenxiaolong** [comment]
@wazeeahmed Basically, you have to look at the TWRP options specified in `BoardConfig.mk` file of the TWRP device tree for your device. For example, the OnePlus One has this section in its TWRP device tree: https://github.com/TeamWin/android_device_oneplus_bacon/blob/e195705c72148725336e2a7494cb7024b3d17939/BoardConfig.mk#L200

Then, you'll need to add the matching option to the DualBootPatcher `.yml` file for your device. This sample file contains the complete list of all the options you can specify for the Boot UI: https://github.com/chenxiaolong/DualBootPatcher/blob/acc1e85f2c87f040c36f8bd9e38a4dc846b2a9a1/data/devices/SAMPLE.yml#L67

---

So in the case of the OnePlus One, the following lines in `BoardConfig.mk` of the TWRP device tree:

```makefile
#TWRP flags
DEVICE_RESOLUTION := 1080x1920
TW_TARGET_USES_QCOM_BSP := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGB_565"
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_NO_USB_STORAGE := true
TW_INCLUDE_CRYPTO := true
BOARD_SUPPRESS_SECURE_ERASE := true
RECOVERY_SDCARD_ON_DATA := true
BOARD_HAS_NO_REAL_SDCARD := true
RECOVERY_VARIANT := twrp
```

would become

```yaml
  boot_ui:
    supported: true
    flags:
      - TW_QCOM_RTC_FIX
    graphics_backends:
      - fbdev
    theme: portrait_hdpi
```

in the DualBootPatcher device definition file.

**Comment by hankching** [comment]
@wazeeahmed 
The link here: 
http://forum.xda-developers.com/showpost.php?p=68565290&postcount=9641

**Comment by wazeeahmed** [comment]
@hankching @chenxiaolong  [here](https://github.com/TeamWin/android_device_google_sprout) is my device twrp source and good news is the bootui configs are same hankching's . Even the flags too and fbdev rendering mode too .

**Comment by chenxiaolong** [comment]
@wazeeahmed Please give the test build at #199 a try.

**Pull request merged**
