### PR TITLE
Add additional codenames to ASUS ZE601KL

### PR DESCRIPTION
**Pull request by addy692**

### CODE REVIEW

**Comment by ndrancs** [comment]
I already add this code, extra part and bootui, please see my commit date.

**Comment by addy692** [comment]
Oh yes i sas that now 
Actually someone on xda was having problem with codenames so in the process of adding codename i thought to add bootui also as it worked on z00l i thought i should work on z00t also 


No prob
 my fault removing my commits

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Pull request merged**
