### PR TITLE
Smartfren Andromax A16C3H

### PR DESCRIPTION
**Pull request by m4l1s**
Dev Please compile new DualBootPatcher.apk for support my device Smartfren Andromax A16C3H

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@noobdev-bot test this please

**Comment by chenxiaolong** [comment]
This build failed due to a missing/empty `architecture` field:

```
02:49:41 [utilities] [100%] Generating device defition JSON file
02:49:41 [utilities] Schema validation failed:
02:49:41 [utilities] {
02:49:41 [utilities]     "type": {
02:49:41 [utilities]         "expected": [
02:49:41 [utilities]             "string"
02:49:41 [utilities]         ],
02:49:41 [utilities]         "actual": "null",
02:49:41 [utilities]         "instanceRef": "#/189/architecture",
02:49:41 [utilities]         "schemaRef": "device.json#/properties/architecture",
02:49:41 [utilities]         "instanceData": null
02:49:41 [utilities]     }
02:49:41 [utilities] }
02:49:41 [utilities] make[2]: *** [data/devices/CMakeFiles/run_devicesgen.dir/build.make:126: data/devices/devices.json] Error 1
02:49:41 [utilities] make[2]: *** Deleting file 'data/devices/devices.json'
02:49:41 [utilities] make[2]: Leaving directory '/home/jenkins-slave/workspace/DualBootPatcher_Build/build_utilities'
02:49:41 [utilities] make[1]: *** [CMakeFiles/Makefile2:1538: data/devices/CMakeFiles/run_devicesgen.dir/all] Error 2
02:49:41 [utilities] make[1]: Leaving directory '/home/jenkins-slave/workspace/DualBootPatcher_Build/build_utilities'
02:49:41 [utilities] make: *** [Makefile:163: all] Error 2
02:49:41 [utilities] make: Leaving directory '/home/jenkins-slave/workspace/DualBootPatcher_Build/build_utilities/data/devices'
```

**Comment by m4l1s** [comment]
How to fix this error

**Comment by yshalsager** [comment]
@m4l1s Your should define device architecture like this
https://github.com/chenxiaolong/DualBootPatcher/commit/1fc7bbd0ebdd3b7f6f416b6d4614f06f8e4fa7de#diff-8488642759945331308a4eecc13e5b27R257
You can find it in build.prop
add it, push changes and your device will be added :smile:

**Comment by chenxiaolong** [comment]
Closing this PR due to a few issues:
* missing `architecture` field
* duplicate `/dev/block/mmcblk1p1` value
* modem block device paths are in the `boot` section

**Pull request closed without merging**
