### PR TITLE
Update oneplus.cpp

### PR DESCRIPTION
**Pull request by hbashton**
add oneplus3

### CODE REVIEW

**Comment by youlunzhai12** [comment]
So, how to build it with this patch? I'm trying to compile a debug build, but the build replies with many errors:

`[ 34%] Building CXX object libmbp/CMakeFiles/mbp-shared.dir/devices/oneplus.cpp.o
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp: In function 'void mbp::addOnePlusDevices(std::vector<mbp::Device*>*)':
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:98:35: error: unable to find numeric literal operator 'operator""_BASE_DIR'
     device->setBlockDevBaseDirs({ 624000_BASE_DIR, BOOTDEVICE_BASE_DIR });
                                   ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:98:85: error: no matching function for call to 'mbp::Device::setBlockDevBaseDirs(<brace-enclosed initializer list>)'
     device->setBlockDevBaseDirs({ 624000_BASE_DIR, BOOTDEVICE_BASE_DIR });
                                                                                     ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:98:85: note: candidate is:
In file included from /home/youlun/DualBootPatcher/libmbp/devices/oneplus.h:24:0,
                 from /home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:20:
/home/youlun/DualBootPatcher/libmbp/include/mbp/device.h:51:10: note: void mbp::Device::setBlockDevBaseDirs(std::vector<std::basic_string<char> >)
     void setBlockDevBaseDirs(std::vector<std::string> dirs);
          ^
/home/youlun/DualBootPatcher/libmbp/include/mbp/device.h:51:10: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'std::vector<std::basic_string<char> >'
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:99:34: error: unable to find numeric literal operator 'operator""_SYSTEM'
     device->setSystemBlockDevs({ 624000_SYSTEM, BOOTDEVICE_SYSTEM,
                                  ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:100:53: error: no matching function for call to 'mbp::Device::setSystemBlockDevs(<brace-enclosed initializer list>)'
                                  "dev/block/sde20" });
                                                     ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:100:53: note: candidate is:
In file included from /home/youlun/DualBootPatcher/libmbp/devices/oneplus.h:24:0,
                 from /home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:20:
/home/youlun/DualBootPatcher/libmbp/include/mbp/device.h:53:10: note: void mbp::Device::setSystemBlockDevs(std::vector<std::basic_string<char> >)
     void setSystemBlockDevs(std::vector<std::string> blockDevs);
          ^
/home/youlun/DualBootPatcher/libmbp/include/mbp/device.h:53:10: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'std::vector<std::basic_string<char> >'
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:101:33: error: unable to find numeric literal operator 'operator""_CACHE'
     device->setCacheBlockDevs({ 624000_CACHE, BOOTDEVICE_CACHE,
                                 ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:102:51: error: no matching function for call to 'mbp::Device::setCacheBlockDevs(<brace-enclosed initializer list>)'
                                 "dev/block/sda3" });
                                                   ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:102:51: note: candidate is:
In file included from /home/youlun/DualBootPatcher/libmbp/devices/oneplus.h:24:0,
                 from /home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:20:
/home/youlun/DualBootPatcher/libmbp/include/mbp/device.h:55:10: note: void mbp::Device::setCacheBlockDevs(std::vector<std::basic_string<char> >)
     void setCacheBlockDevs(std::vector<std::string> blockDevs);
          ^
/home/youlun/DualBootPatcher/libmbp/include/mbp/device.h:55:10: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'std::vector<std::basic_string<char> >'
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:103:32: error: unable to find numeric literal operator 'operator""_USERDATA'
     device->setDataBlockDevs({ 624000_USERDATA, BOOTDEVICE_USERDATA,
                                ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:104:52: error: no matching function for call to 'mbp::Device::setDataBlockDevs(<brace-enclosed initializer list>)'
                                "/dev/block/sda15" });
                                                    ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:104:52: note: candidate is:
In file included from /home/youlun/DualBootPatcher/libmbp/devices/oneplus.h:24:0,
                 from /home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:20:
/home/youlun/DualBootPatcher/libmbp/include/mbp/device.h:57:10: note: void mbp::Device::setDataBlockDevs(std::vector<std::basic_string<char> >)
     void setDataBlockDevs(std::vector<std::string> blockDevs);
          ^
/home/youlun/DualBootPatcher/libmbp/include/mbp/device.h:57:10: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'std::vector<std::basic_string<char> >'
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:105:32: error: unable to find numeric literal operator 'operator""_BOOT'
     device->setBootBlockDevs({ 624000_BOOT, BOOTDEVICE_BOOT,
                                ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:106:52: error: no matching function for call to 'mbp::Device::setBootBlockDevs(<brace-enclosed initializer list>)'
                                "/dev/block/sde18" });
                                                    ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:106:52: note: candidate is:
In file included from /home/youlun/DualBootPatcher/libmbp/devices/oneplus.h:24:0,
                 from /home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:20:
/home/youlun/DualBootPatcher/libmbp/include/mbp/device.h:59:10: note: void mbp::Device::setBootBlockDevs(std::vector<std::basic_string<char> >)
     void setBootBlockDevs(std::vector<std::string> blockDevs);
          ^
/home/youlun/DualBootPatcher/libmbp/include/mbp/device.h:59:10: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'std::vector<std::basic_string<char> >'
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:107:36: error: unable to find numeric literal operator 'operator""_RECOVERY'
     device->setRecoveryBlockDevs({ 624000_RECOVERY, BOOTDEVICE_RECOVERY,
                                    ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:108:56: error: no matching function for call to 'mbp::Device::setRecoveryBlockDevs(<brace-enclosed initializer list>)'
                                    "/dev/block/sde21" });
                                                        ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:108:56: note: candidate is:
In file included from /home/youlun/DualBootPatcher/libmbp/devices/oneplus.h:24:0,
                 from /home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:20:
/home/youlun/DualBootPatcher/libmbp/include/mbp/device.h:61:10: note: void mbp::Device::setRecoveryBlockDevs(std::vector<std::basic_string<char> >)
     void setRecoveryBlockDevs(std::vector<std::string> blockDevs);
          ^
/home/youlun/DualBootPatcher/libmbp/include/mbp/device.h:61:10: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'std::vector<std::basic_string<char> >'
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:110:9: error: unable to find numeric literal operator 'operator""_ABOOT'
         624000_ABOOT, "/dev/block/sde15",
         ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:111:9: error: unable to find numeric literal operator 'operator""_LOGO'
         624000_LOGO, "/dev/block/sde17",
         ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:112:9: error: unable to find numeric literal operator 'operator""_MODEM'
         624000_MODEM, "/dev/block/sde11",
         ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:113:9: error: unable to find numeric literal operator 'operator""_RPM'
         624000_RPM, "/dev/block/sde1",
         ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:114:9: error: unable to find numeric literal operator 'operator""_TZ'
         624000_TZ, "/dev/block/sde3"
         ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:115:6: error: no matching function for call to 'mbp::Device::setExtraBlockDevs(<brace-enclosed initializer list>)'
     });
      ^
/home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:115:6: note: candidate is:
In file included from /home/youlun/DualBootPatcher/libmbp/devices/oneplus.h:24:0,
                 from /home/youlun/DualBootPatcher/libmbp/devices/oneplus.cpp:20:
/home/youlun/DualBootPatcher/libmbp/include/mbp/device.h:63:10: note: void mbp::Device::setExtraBlockDevs(std::vector<std::basic_string<char> >)
     void setExtraBlockDevs(std::vector<std::string> blockDevs);
          ^
/home/youlun/DualBootPatcher/libmbp/include/mbp/device.h:63:10: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'std::vector<std::basic_string<char> >'
libmbp/CMakeFiles/mbp-shared.dir/build.make:1046: recipe for target 'libmbp/CMakeFiles/mbp-shared.dir/devices/oneplus.cpp.o' failed
make[5]: *** [libmbp/CMakeFiles/mbp-shared.dir/devices/oneplus.cpp.o] Error 1
CMakeFiles/Makefile2:328: recipe for target 'libmbp/CMakeFiles/mbp-shared.dir/all' failed
make[4]: *** [libmbp/CMakeFiles/mbp-shared.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make[3]: *** [all] Error 2
android/CMakeFiles/android-app_x86_64.dir/build.make:110: recipe for target 'android/android-app_x86_64-prefix/src/android-app_x86_64-stamp/android-app_x86_64-build' failed
make[2]: *** [android/android-app_x86_64-prefix/src/android-app_x86_64-stamp/android-app_x86_64-build] Error 2
CMakeFiles/Makefile2:931: recipe for target 'android/CMakeFiles/android-app_x86_64.dir/all' failed
make[1]: *** [android/CMakeFiles/android-app_x86_64.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by chenxiaolong** [comment]
@youlunzhai12 That message is actually from my build server. It will automatically make that comment in every pull request.

It looks like you're not defining the `624000_*` paths anywhere. You'll want to put those in `libmbp/devices/paths.h`.

**Comment by matze19999** [comment]
When do you want to get this working?:)

**Comment by Rohk25** [comment]
I want to get this working right now but I can't

**Comment by chenxiaolong** [comment]
Closing as I did this separately in https://github.com/chenxiaolong/DualBootPatcher/commit/fb2833eda8c8886bee0ab190f67b7f6ec93f63cf

**Pull request closed without merging**
