### PR TITLE
data: 01_galaxy_note.yml: Fix invalid indentation

### LINKED ISSUE #662: Samsung Galaxy Note line support
I found out my Samsung Galaxy Note 3 hlte has been removed from the list of supported devices after 9.2.0.r203.gb7e4045d. There might be an indentation issue at data/devices/samsung/01_galaxy_note.yml since every device after Note 2 (Exynos) is no longer supported after commit b7e4045.

### PR DESCRIPTION
**Pull request by mikko100**
Fixes #662

### CODE REVIEW

**Comment by MisiekDP** [comment]
This commit can repair Note3 visibility in app. Please add this commit, chen :)

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
Hmm, I need to check the YAML parser. Not sure why it accepted the old file with the incorrect indentation.

**Comment by chenxiaolong** [comment]
Unfortunately, [yaml-cpp](https://github.com/jbeder/yaml-cpp) doesn't detect the incorrect indentation as an error. For example, if I try loading the file with:
```cpp
#include <iostream>

#include <cstdlib>

#include <yaml-cpp/yaml.h>

int main(int argc, char *argv[])
{
    if (argc != 2) {
        std::cerr << "Usage: " << argv[0] << " <file>\n";
        return EXIT_FAILURE;
    }

    YAML::Node root = YAML::LoadFile(argv[1]);
    std::cout << root;
    return EXIT_SUCCESS;
}
```
and run it:
```
[/tmp] ./a.out /stuff/Android/DualBootPatcher/data/devices/samsung/01_galaxy_note.yml | grep name:
  name: Samsung Galaxy Note 2
  name: Samsung Galaxy Note 2 (Exynos)
```
then it simply stops parsing right before Note 3 item in the YAML file. It can't detect that the file is bad.

**Comment by MisiekDP** [comment]
Wow, what a fast reply :D
Is it possible to compile a new version with this commit? :)
I am all time on version r202 and I have a problem with flashing SuperSU (maybe newer versions have fixed this problem).
Thx! :)
Btw. can I compile this code in Android Studio (it is your code so I need to ask :))?

**Comment by chenxiaolong** [comment]
A new version is automatically built when I merge a pull request. The new version should be available at https://dbp.noobdev.io/downloads/ in a few minutes :)

**Comment by MisiekDP** [comment]
So this incorrect indentation isn't a problem? Hmm :/ I compared devices (Galaxy S and Galaxy Note) and I found a one incorrect indentation after Note 2.

**Comment by chenxiaolong** [comment]
Sorry, I'm not sure I understand your question. The new version with the indentation fix (`9.2.0.r281.g8bddd382`) is now available.

**Comment by MisiekDP** [comment]
Heh so I misunderstood your answer :D Sorry, I will try ;)
Thanks! :)

**Comment by MisiekDP** [comment]
It works again! :)
Thank you!

bez nazwy

**Pull request merged**
