### PR TITLE
external: Update flatbuffers to 1.8.0

### PR DESCRIPTION
**Pull request by chenxiaolong**
Signed-off-by: Andrew Gunnerson <chenxiaolong@cxl.epac.to>

### CODE REVIEW

**Comment by chenxiaolong** [comment]
This is currently blocked by https://github.com/google/flatbuffers/issues/4579

**Comment by Caio99BR** [comment]
Commit merged, building is now possible.

**Comment by Caio99BR** [comment]
Hey check it!

**Comment by Caio99BR** [comment]
GitHub calling @chenxiaolong, please reply..

**Comment by chenxiaolong** [comment]
Superseded by #1101.

**Pull request closed without merging**
