### PR TITLE
add sony xperia sp support

### PR DESCRIPTION
**Pull request by darjwx**
I have closed the other pull request and I have done this one, more clean xD.
Now should be fine.

### CODE REVIEW

**Comment by Caio99BR** [comment]
https://github.com/CyanogenMod/android_device_sony_huashan/blob/cm-12.1/rootdir/fstab.qcom
You checked this?

**Comment by darjwx** [comment]
@Caio99BR I used this app  to check the partitions: https://play.google.com/store/apps/details?id=com.cls.partition

**Comment by Caio99BR** [comment]
I mean the name partitions is wrong see fstab of your device.

**Comment by darjwx** [comment]
Updated with the new changes for sony devices.

**Comment by chenxiaolong** [comment]
This has been included in #174.

**Pull request closed without merging**
