### PR TITLE
Added Lenovo A6000

### PR DESCRIPTION
**Pull request by varunhardgamer**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
@varunhardgamer The build failed because `/dev/block/mmcblk1p1` shows up twice in the list. Can you remove one of them?
```
17:27:57 [utilities] Schema validation failed:
17:27:57 [utilities] - Schema URI: #
17:27:57 [utilities] - Schema keyword: uniqueItems
17:27:57 [utilities] - Document URI: #/84/block_devs/extra/27
17:27:57 [utilities] Parent of offending JSON value:
17:27:57 [utilities] [
17:27:57 [utilities]     "/dev/block/mmcblk1p1",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/DDR",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/aboot",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/abootbak",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/config",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/fsc",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/fsg",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/hyp",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/hypbak",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/keystore",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/misc",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/modem",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/modemst1",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/modemst2",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/oem",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/pad",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/persist",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/rpm",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/rpmbak",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/sbl1",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/sbl1bak",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/sec",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/splash",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/ssd",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/tz",
17:27:57 [utilities]     "/dev/block/platform/soc.0/7824900.sdhci/by-name/tzbak",
17:27:57 [utilities]     "/dev/block/mmcblk1",
17:27:57 [utilities]     "/dev/block/mmcblk1p1"
17:27:57 [utilities] ]
```

**Comment by varunhardgamer** [comment]
@chenxiaolong Removed one of the conflict

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Pull request merged**
