### PR TITLE
Add support for GM4G

### PR DESCRIPTION
**Pull request by MSF-Jarvis**

### CODE REVIEW

**Comment by Caio99BR** [comment]
It's a Google device not Nexus :P

**Comment by wazeeahmed** [comment]
He already mentioned it as a google device . There was no indication it's a nexus . But it's a cousin of nexus . Infact it received android n update much sooner than anticipated (1 day after new os launch) .

**Comment by Caio99BR** [comment]
Because him is maintained by Google? Not look obvious?

**Comment by wazeeahmed** [comment]
Of course it's maintained by google . OEM's are just puppets here . Those devices followed google's instruction and their estimation too . Pure aosp like nexus but not nexus . You've to understand the point . And nexus devices are exactly the same . But it's much more of a power house than android one devices and lil bit of expensive too . But android one gets mentioned in every update news right after nexus . So yeah they are cousins but not same .

**Comment by MSF-Jarvis** [comment]
@Caio99BR GM4G runs off a standard Snapdragon 615 chipset and is internally similar to the Wileyfox Crackling, if you want I can move this commit onto a wileyfox config if it exists.

**Comment by Caio99BR** [comment]
But it is Google device, if stock have Google in build.prop it's a Google device

@chenxiaolong why not add to Milestone 9?

**Comment by chenxiaolong** [comment]
@Caio99BR I have not merged this because I think the description could be clearer. Looking at Wikipedia, [there are many devices that are all known as "Android One Second Generation"](https://en.wikipedia.org/wiki/Android_One#Second_generation). The name should be more specific (unless, of course, the partitions are the same for all the devices).

**Comment by wazeeahmed** [comment]
@chenxiaolong  gm4g is codenamed as seed . ll second generation android one is codenamed as seed even medietek variants too . Just mtk was to be added with seed .

**Comment by hankching** [comment]
@MSF-Jarvis 
According to above article, GM4G is Snapdragon 410 and GM5Plus is Snapdragon 617. 
Secondly,  Wileyfox Swift already exists and codename is Crackling as located at /data/devices/Wileyfox.yml. BUT which based on MTK chip.
Thirdly, > device->setName("Google Android One Second Generation"); which should be changed because it includes Lava Pixel V1, Infinix Hot 2 X510, etc. Therefore chenxiaolong needs you change it.

**Comment by MSF-Jarvis** [comment]
Agree to the name change, been meaning to do it for a while. I've lost
personal interest in getting the GM4G supported so considered this
abandoned.

**Comment by chenxiaolong** [comment]
@MSF-Jarvis Sorry to hear you lost interest in getting your device supported.

If you ever feel like working on this again, I've created #193 (retaining your authorship), which adapts your changes to work with the upcoming version 9.0.0.

**Pull request closed without merging**
