### PR TITLE
Add Samsung Galaxy J5 2017 (Exynos)//Samsung Galaxy A8/A8+ 2018 (Exynos)

### PR DESCRIPTION
**Pull request by ananjaser1211**
Support for ALL J5 Pro (2017) Variants.
Edits
Support for A8/A8+ 2018

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@noobdev-bot test this please

**Comment by chenxiaolong** [comment]
@noobdev-bot retest this please

**Comment by chenxiaolong** [comment]
@noobdev-bot retest this please

**Comment by chenxiaolong** [comment]
@noobdev-bot retest this please

**Comment by ananjaser1211** [comment]
Thanks for merging/correcting.

**Pull request merged**
