### PR TITLE
Request for wipe option in bootui

### PR DESCRIPTION
**Pull request by wazeeahmed**
As some custom roms like rr got updated recently , I need to wipe primary rom . if there was wipe option in bootui . This might turnout to be quite helpful . So that my secondary rom won't be disrupted because of primary rom .

### CODE REVIEW

**Comment by Caio99BR** [comment]
Again it :(

**Comment by Caio99BR** [comment]
WTF??

**Comment by chenxiaolong** [comment]
@Caio99BR I did not merge this haha. GitHub is being dumb.

**Comment by Caio99BR** [comment]
I looked and said "What?"
But now, it's bump up, YEAH!!!!
Good to see you're back to business, not for much time XD

Em seg, 17 de out de 2016 00:28, Andrew Gunnerson <notifications@github.com>
escreveu:

**Pull request merged**
