### PR TITLE
Devices: Add Support For Nokia X2, Samsung Galaxy Win/Core, Lenovo A706/A760 and Enable bootui for Mi Max

### PR DESCRIPTION
**Pull request by yshalsager**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chenxiaolong** [comment]
The build failed because `ara` is missing in `graphics_backends` boot UI options.

**Comment by yshalsager** [comment]
Fixed, thanks!

**Comment by yshalsager** [comment]
@Chenxiaolong please review this

**Comment by yshalsager** [comment]
@Chenxiaolong please tell me if anything must be changed

**Comment by yshalsager** [comment]
I start adding new devices, so i'll create new pull

**Pull request closed without merging**
