### PR TITLE
Add Huawei P8 support

### PR DESCRIPTION
**Pull request by erayrafet**

### CODE REVIEW

**Comment by erayrafet** [comment]
Would you consider merging my commit, because it's kinda urgent. I need it to test some ROMs.

**Comment by chenxiaolong** [comment]
@noobdev-bot test this please

**Comment by erayrafet** [comment]
I'm getting a force close whenever I enter the ROMs section.
[https://drive.google.com/file/d/1HnLs1kWxITeJx4TsMy5sDAsy3yncrvAL/view?usp=drivesdk](url)

**Comment by erayrafet** [comment]
On version 9.3.0.r751.g4ddee20f-snapshot I can't install mbtool and I'm losing root access from SuperSU.
https://drive.google.com/file/d/1eqCvlwF2h-K6bpMYXg1AUX1mHZ3jk878/view?usp=drivesdk

**Comment by erayrafet** [comment]
Otherwise Dual Boot works fine.

**Comment by erayrafet** [comment]
Even if I don't click update ramdisk, when I switch to the Secondary ROM, it corrupts my Primary ROMs boot.img. From the logs you can see that /boot is low in space.

**Comment by erayrafet** [comment]
Are NTFS SD cards supported or it's a bug?
https://drive.google.com/file/d/1HJE2TN3zRYlbBHT2dTRcaoPGfCCwp2fj/view?usp=drivesdk

**Pull request merged**
