### PR TITLE
Additional partitiom detailes for ze550kl

### PR DESCRIPTION
**Pull request by addy692**
Thanks in advancr

### CODE REVIEW

**Comment by ndrancs** [comment]
i tested it before (the bootui code), on my z00t phone, but the touch doesn't work when in bootui and after boot to home screen. Must power off the phone via press and hold power button. Did it work in your z00l phone?

**Comment by addy692** [comment]
I will tell when the changes are merged in the next build

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by addy692** [comment]
Boot ui is working in my Z00L

**Comment by ndrancs** [comment]
is the touch screen working too?

**Comment by addy692** [comment]
Yup touch is working 
And switching rom also

**Comment by ndrancs** [comment]
Ok. Thanks i will compile it again with extra partition for z00t. And boot ui.

**Pull request merged**
