### PR TITLE
add support to galaxy s8+ (snapdragon)

### PR DESCRIPTION
**Pull request by utheeo**
for the SM-G9550 128GB Snapdragon model

### CODE REVIEW

**Comment by yshalsager** [comment]
@utheeo it's already supported
https://github.com/chenxiaolong/DualBootPatcher/blob/master/data/devices/samsung/00_galaxy_s.yml#L1065

**Comment by utheeo** [comment]
@yshalsager my device isn't recognized where i couldn't update ramdisk. Maybe the codename 'dream2qltechn' needs to be added for it to work?
screenshot_20180109-085842 1
screenshot_20180109-085855 1
screenshot_20180109-085914 1
screenshot_20180109-085955 1
[boot-ui-action[1].log](https://github.com/chenxiaolong/DualBootPatcher/files/1615383/boot-ui-action.1.log)
[ramdisk-update[1].log](https://github.com/chenxiaolong/DualBootPatcher/files/1615385/ramdisk-update.1.log)

**Comment by yshalsager** [comment]
Yeah, I'll add it now

**Comment by chenxiaolong** [comment]
Added by @yshalsager in #960.

**Pull request closed without merging**
