### PR TITLE
Android GUI: Graceful fallback from ACTION_OPEN_DOCUMENT on 4.4+

### PR DESCRIPTION
**Pull request by chenxiaolong**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
Test build is available here when the build completes: https://jenkins.noobdev.io/job/DualBootPatcher_Build/target=android-all-gcc/158/

**Comment by webmaster33** [comment]
Better. Doesn't crash suddenly when tapping + file add sign, but later, when the file is selected in file manager. 

java.lang.NullPointerException
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment.onQueriedMetadata(PatchFileFragment.java:830)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment.access$2400(PatchFileFragment.java:86)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment$GetUriMetadataTask.onPostExecute(PatchFileFragment.java:1111)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment$GetUriMetadataTask.onPostExecute(PatchFileFragment.java:1066)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5139)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)

> Better. Doesn't crash suddenly when tapping + file add sign, but later, when the file is selected in file manager. 
> 
> java.lang.NullPointerException
> 	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment.onQueriedMetadata(PatchFileFragment.java:830)
> 	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment.access$2400(PatchFileFragment.java:86)
> 	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment$GetUriMetadataTask.onPostExecute(PatchFileFragment.java:1111)
> 	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment$GetUriMetadataTask.onPostExecute(PatchFileFragment.java:1066)
> 	at android.os.AsyncTask.finish(AsyncTask.java:632)
> 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
> 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:136)
> 	at android.app.ActivityThread.main(ActivityThread.java:5139)
> 	at java.lang.reflect.Method.invokeNative(Native Method)
> 	at java.lang.reflect.Method.invoke(Method.java:515)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
> 	at dalvik.system.NativeStart.main(Native Method)
> 

Better. Doesn't crash suddenly when tapping + file add sign, but later, when the file is selected in file manager. 

java.lang.NullPointerException
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment.onQueriedMetadata(PatchFileFragment.java:830)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment.access$2400(PatchFileFragment.java:86)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment$GetUriMetadataTask.onPostExecute(PatchFileFragment.java:1111)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment$GetUriMetadataTask.onPostExecute(PatchFileFragment.java:1066)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5139)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by chenxiaolong** [comment]
Hmm, the ROM doesn't appear to return the filename of the file you selected. I'm not sure why MIUI doesn't behave like the Android documentation describes.

Can you give me the link to the ROM you're running? I'll try it on my S4 and see if I can find a workaround to get this working.

**Comment by webmaster33** [comment]
I use MIUI V5 4.9.26 based on Android 4.4.4 for Samsung Galaxy S4 i9505. 
[ROM][4.4.4] MIUI V5 i9505 4.9.26 jflte (MIUI Stock Rom with small changes and Game Lag Fix)
MIUI_V5_i9505_v4.4.4_jflte_4.9.26.zip

Looking for a link...

**Comment by webmaster33** [comment]
http://miui-for-i9505.blogspot.nl/2014/10/rom-miui-v5-update-to-4926-stock-and.html?m=1

**Comment by webmaster33** [comment]
Was it fixed?

**Comment by webmaster33** [comment]
Still crashing:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/jflte/jflte:4.4.4/KTU84Q/jflte:user/release-keys'
Revision: '11'
pid: 14093, tid: 14093, name: ogle.android.gm  >>> com.google.android.gm <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    r0 fffffffc  r1 beaff318  r2 00000010  r3 0000010b
    r4 715e4298  r5 00000000  r6 715e42ac  r7 000000fc
    r8 715e42e0  r9 00000014  sl 414c84f0  fp beaff48c
    ip beaff318  sp beaff2f8  lr 400b518f  pc 4004c770  cpsr 200f0010
    d0  000052bdae9c9936  d1  0000000000000000
    d2  000003e800000000  d3  0000000000000014
    d4  0009228000000000  d5  0000000010001000
    d6  0000000000000000  d7  0000000000000000
    d8  00000000000005c5  d9  4468800044a6a000
    d10 421c000044b8a000  d11 00000000440e8000
    d12 0000000000000000  d13 0000000000000000
    d14 0000000000000000  d15 0000000000000000
    d16 ffffffffffb3b4c0  d17 000052bdaee8e476
    d18 0000000000000000  d19 0061007200470049
    d20 0063006900680070  d21 0066006600750042
    d22 0072005000720065  d23 006300750064006f
    d24 0078007700750076  d25 0079007a007a0079
    d26 0000000000000000  d27 0000000000000000
    d28 0048004700450046  d29 0049004a004a0049
    d30 007a007a007a007a  d31 0000000000000000
    scr 28000017

backtrace:
    #00  pc 00021770  /system/lib/libc.so (epoll_wait+12)
    #01  pc 0001118b  /system/lib/libutils.so (android::Looper::pollInner(int)+98)
    #02  pc 000113b1  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+92)
    #03  pc 0006fdd5  /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv*, int)+22)
    #04  pc 0001ea50  /system/lib/libdvm.so (dvmPlatformInvoke+116)
    #05  pc 0004f667  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
    #06  pc 00000214  /dev/ashmem/dalvik-jit-code-cache (deleted)

code around pc:
    4004c750 e1a0700c e3700a01 912fff1e e2600000  
    4004c760 ea007011 e1a0c007 e3a070fc ef000000  
    4004c770 e1a0700c e3700a01 912fff1e e2600000  
    4004c780 ea007009 e1a0c007 e3a07f4f ef000000  
    4004c790 e1a0700c e3700a01 912fff1e e2600000  
    4004c7a0 ea007001 e1a0c007 e59f7014 ef000000  
    4004c7b0 e1a0700c e3700a01 912fff1e e2600000  
    4004c7c0 ea006ff9 0000013d e1a0c007 e59f7014  
    4004c7d0 ef000000 e1a0700c e3700a01 912fff1e  
    4004c7e0 e2600000 ea006ff0 0000013e e1a0c007  
    4004c7f0 e3a070a8 ef000000 e1a0700c e3700a01  
    4004c800 912fff1e e2600000 ea006fe7 e1a0c007  
    4004c810 e3a07f59 ef000000 e1a0700c e3700a01  
    4004c820 912fff1e e2600000 ea006fdf e1a0c007  
    4004c830 e59f7014 ef000000 e1a0700c e3700a01  
    4004c840 912fff1e e2600000 ea006fd7 000f0005  

code around lr:
    400b516c 46402500 f7ffaf08 2301fa01 f8842210  
    400b517c 4639302d 65e54633 f1046b20 f7fa0614  
    400b518c f884e80c 4681502d f7fd4630 45a9fee4  
    400b519c f7f9da12 6807ee40 d1022f04 37fff04f  
    400b51ac 4963e056 0703f06f 68034a62 44792005  
    400b51bc f7f9447a e04bedee f8dfd048 f8dfa17c  
    400b51cc 485fb17c 44fb44fa 90054478 68e00129  
    400b51dc 587b187a 42826892 07d9d10c 4620d503  
    400b51ec fddaf7ff 4a57e02e 46592005 f7f9447a  
    400b51fc e027edd0 f1044611 93030034 f7ff9204  
    400b520c 2800ff07 9b039904 f003db16 075a0101  
    400b521c f041bf48 071a0102 f041bf48 06db0104  
    400b522c bf486ba3 0108f041 fb022214 46203300  
    400b523c f7ff1d1a e005ff56 20059100 46529905  
    400b524c eda6f7f9 454d3501 e7a7dbc0 0702f06f  
    400b525c 32fff04f 4300f06f 2318e9c4 0918f104

**Comment by webmaster33** [comment]
Any news about fixing this bug?

**Pull request merged**
