### PR TITLE
libmbp: Add support for LG L7 Brothers

### PR DESCRIPTION
**Pull request by Caio99BR**
Add support LG L7 First Gen and Second Gen

### CODE REVIEW

**Comment by Caio99BR** [comment]
@chenxiaolong any way to merge
Only the L7 (First Gen) was tested, the LG L7II not have tested but because i have participated of build of most of him, i think this support all ROMs, and this is the pattern of most of LG Roms Stock/Custom.

**Comment by zeeshanhussain** [comment]
@Caio99BR  he is on a vacation :)

**Comment by Caio99BR** [comment]
@zeeshanhussain I know :P

**Comment by Caio99BR** [comment]
@chenxiaolong any way to merge?

**Pull request merged**
