### PR TITLE
mbtool: mount_fstab.cpp: Try next vold pattern if first existing pattern fails to mount

### PR DESCRIPTION
**Pull request by chenxiaolong**

### CODE REVIEW

**Comment by chenxiaolong** [comment]
Test build: https://jenkins.noobdev.io/job/DualBootPatcher_Build/525/label_exp=dualbootpatcher-builder,target=android-all-gcc/

**Comment by webmaster33** [comment]
Still doesn't boot. 
The 10 attempts are done, but external sdcard is not found.

**Comment by chenxiaolong** [comment]
@webmaster33 Can you try this new test build? https://jenkins.noobdev.io/job/DualBootPatcher_Build/526/label_exp=dualbootpatcher-builder,target=android-all-gcc/

**Comment by chenxiaolong** [comment]
New test build with new fuse-exfat driver (version 1.2.6): https://jenkins.noobdev.io/job/DualBootPatcher_Build/528/label_exp=dualbootpatcher-builder,target=android-all-gcc/

**Comment by meudayhegde** [comment]
This build working on coolpad
Please merge this

**Comment by webmaster33** [comment]
@chenxiaolong:
+1 to merge the branch. 

Although it did not solve the booting problem with external sdcard having exFAT format, so I formatted the card to FAT32, it works fine. 

But solved the problem of flashing rom to external sdcard too long (6-9 hours). 

With the new exFAT 1.2.6 driver the in-app flashing (DBP r157) takes less than 10 minutes. Not sure tough though, if this related to the new driver.

**Pull request merged**
