### PR TITLE
Add support to HUAWEI Y635

### PR DESCRIPTION
**Pull request by R4G2R**
Based on @CarlosArriagaCM pull request(#223) on original project but with the new devices file system.

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

_(This is a message for the build server.)_

**Comment by R4G2R** [comment]
I tried the build and when I install any rom on dual raises the same error. This is the log: 

```
[D] Initialized installer for zip file: /storage/sdcard1/cmcarlos/cm-13.0-20160916-UNOFFICIAL-hwY635_dual.zip
[D] [Installer] Initialization stage
[D] [Installer] Chroot creation stage
[V] Creating chroot environment
[D] Running executable: mount
Usage: mount [-r] [-w] [-o options] [-t type] device directory
[D] Running executable: mount
[D] Running executable: mount
Usage: mount [-r] [-w] [-o options] [-t type] device directory
[D] Running executable: mount
Usage: mount [-r] [-w] [-o options] [-t type] device directory
[D] Not mounting EFS partition because this is not a Samsung device
[D] [Installer] Environment set up stage
[D] [Installer] Device verification stage
[D] libmbp version: 9.0.0
[D] ro.product.device = Y635-L01
[D] ro.build.product = Y635-L01
[D] ro.patcher.device = 
[D] Target device = hwY635
[D] Boot block device: /dev/block/platform/7824900.sdhci/by-name/boot
[D] Recovery block device: /dev/block/platform/7824900.sdhci/by-name/recovery
[D] System block device: /dev/block/platform/7824900.sdhci/by-name/system
[D] Copied /dev/block/platform/7824900.sdhci/by-name/boot to the chroot
[D] Copied /dev/block/mmcblk0p18 to the chroot
[D] Copied /dev/block/platform/7824900.sdhci/by-name/recovery to the chroot
[D] Copied /dev/block/mmcblk0p19 to the chroot
[D] Symlinked /mb/loop.system to /chroot/dev/block/platform/7824900.sdhci/by-name/system
[D] Symlinked /mb/loop.system to /chroot/dev/block/mmcblk0p23
[D] Boot image is a plain boot image
[D] Found Android boot image header at: 0
[D] - magic:        ANDROID!
[D] - kernel_size:  5536464
[D] - kernel_addr:  0x80008000
[D] - ramdisk_size: 4118755
[D] - ramdisk_addr: 0x81000000
[D] - second_size:  0
[D] - second_addr:  0x80f00000
[D] - tags_addr:    0x80000100
[D] - page_size:    2048
[D] - dt_size:      7436288
[D] - unused:       0x00000000
[D] - name:         
[D] - cmdline:      console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom user_debug=30 msm_rtb.filter=0x3F ehci-hcd.park=3 androidboot.bootdevice=7824900.sdhci lpm_levels.sleep_disabled=1 androidboot.selinux=enforcing
[D] - id:           970a10540ab59d03573d72b2eee2b2385bba39f8000000000000000000000000
[E] Copying from recovery: default.recovery.prop
[E] Copying from recovery: sbin/[
[E] Copying from recovery: sbin/[[
[E] Copying from recovery: sbin/adbd
[E] Copying from recovery: sbin/adjtimex
[E] Copying from recovery: sbin/arp
[E] Copying from recovery: sbin/ash
[E] Copying from recovery: sbin/awk
[E] Copying from recovery: sbin/base64
[E] Copying from recovery: sbin/basename
[E] Copying from recovery: sbin/bbconfig
[E] Copying from recovery: sbin/blkid
[E] Copying from recovery: sbin/blockdev
[E] Copying from recovery: sbin/brctl
[E] Copying from recovery: sbin/bu
[E] Copying from recovery: sbin/bunzip2
[E] Copying from recovery: sbin/busybox
[E] Copying from recovery: sbin/bzcat
[E] Copying from recovery: sbin/bzip2
[E] Copying from recovery: sbin/cal
[E] Copying from recovery: sbin/cat
[E] Copying from recovery: sbin/catv
[E] Copying from recovery: sbin/chattr
[E] Copying from recovery: sbin/chcon
[E] Copying from recovery: sbin/chgrp
[E] Copying from recovery: sbin/chmod
[E] Copying from recovery: sbin/chown
[E] Copying from recovery: sbin/chroot
[E] Copying from recovery: sbin/chvt
[E] Copying from recovery: sbin/clear
[E] Copying from recovery: sbin/cmp
[E] Copying from recovery: sbin/comm
[E] Copying from recovery: sbin/cp
[E] Copying from recovery: sbin/cpio
[E] Copying from recovery: sbin/crond
[E] Copying from recovery: sbin/crontab
[E] Copying from recovery: sbin/cut
[E] Copying from recovery: sbin/date
[E] Copying from recovery: sbin/dc
[E] Copying from recovery: sbin/dd
[E] Copying from recovery: sbin/deallocvt
[E] Copying from recovery: sbin/depmod
[E] Copying from recovery: sbin/devmem
[E] Copying from recovery: sbin/df
[E] Copying from recovery: sbin/diff
[E] Copying from recovery: sbin/dirname
[E] Copying from recovery: sbin/dmesg
[E] Copying from recovery: sbin/dnsd
[E] Copying from recovery: sbin/dos2unix
[E] Copying from recovery: sbin/du
[E] Copying from recovery: sbin/dump_image
[E] Copying from recovery: sbin/e2fsck
[E] Copying from recovery: sbin/echo
[E] Copying from recovery: sbin/ed
[E] Copying from recovery: sbin/egrep
[E] Copying from recovery: sbin/env
[E] Copying from recovery: sbin/erase_image
[E] Copying from recovery: sbin/exfat-fuse
[E] Copying from recovery: sbin/expand
[E] Copying from recovery: sbin/expr
[E] Copying from recovery: sbin/false
[E] Copying from recovery: sbin/fatlabel
[E] Copying from recovery: sbin/fbsplash
[E] Copying from recovery: sbin/fdisk
[E] Copying from recovery: sbin/fgconsole
[E] Copying from recovery: sbin/fgrep
[E] Copying from recovery: sbin/find
[E] Copying from recovery: sbin/findfs
[E] Copying from recovery: sbin/flash_image
[E] Copying from recovery: sbin/flash_lock
[E] Copying from recovery: sbin/flash_unlock
[E] Copying from recovery: sbin/flashcp
[E] Copying from recovery: sbin/flock
[E] Copying from recovery: sbin/fold
[E] Copying from recovery: sbin/free
[E] Copying from recovery: sbin/freeramdisk
[E] Copying from recovery: sbin/fsck.exfat
[E] Copying from recovery: sbin/fsck.f2fs
[E] Copying from recovery: sbin/fsck.fat
[E] Copying from recovery: sbin/fstrim
[E] Copying from recovery: sbin/fsync
[E] Copying from recovery: sbin/ftpget
[E] Copying from recovery: sbin/ftpput
[E] Copying from recovery: sbin/fuser
[E] Copying from recovery: sbin/getenforce
[E] Copying from recovery: sbin/getopt
[E] Copying from recovery: sbin/getprop
[E] Copying from recovery: sbin/getsebool
[E] Copying from recovery: sbin/grep
[E] Copying from recovery: sbin/groups
[E] Copying from recovery: sbin/gunzip
[E] Copying from recovery: sbin/gzip
[E] Copying from recovery: sbin/halt
[E] Copying from recovery: sbin/head
[E] Copying from recovery: sbin/healthd
[E] Copying from recovery: sbin/hexdump
[E] Copying from recovery: sbin/hwclock
[E] Copying from recovery: sbin/id
[E] Copying from recovery: sbin/ifconfig
[E] Copying from recovery: sbin/inetd
[E] Copying from recovery: sbin/insmod
[E] Copying from recovery: sbin/install
[E] Copying from recovery: sbin/ionice
[E] Copying from recovery: sbin/iostat
[E] Copying from recovery: sbin/ip
[E] Copying from recovery: sbin/kill
[E] Copying from recovery: sbin/killall
[E] Copying from recovery: sbin/killall5
[E] Copying from recovery: sbin/less
[E] Copying from recovery: sbin/libaosprecovery.so
[E] Copying from recovery: sbin/libbacktrace.so
[E] Copying from recovery: sbin/libblkid.so
[E] Copying from recovery: sbin/libbmlutils.so
[E] Copying from recovery: sbin/libc.so
[E] Copying from recovery: sbin/libcrecovery.so
[E] Copying from recovery: sbin/libcutils.so
[E] Copying from recovery: sbin/libdl.so
[E] Copying from recovery: sbin/libexfat_twrp.so
[E] Copying from recovery: sbin/libext2_blkid.so
[E] Copying from recovery: sbin/libext2_com_err.so
[E] Copying from recovery: sbin/libext2_e2p.so
[E] Copying from recovery: sbin/libext2_profile.so
[E] Copying from recovery: sbin/libext2_quota.so
[E] Copying from recovery: sbin/libext2_uuid.so
[E] Copying from recovery: sbin/libext2fs.so
[E] Copying from recovery: sbin/libext4_utils.so
[E] Copying from recovery: sbin/libflashutils.so
[E] Copying from recovery: sbin/libft2.so
[E] Copying from recovery: sbin/libfusesideload.so
[E] Copying from recovery: sbin/libgccdemangle.so
[E] Copying from recovery: sbin/liblog.so
[E] Copying from recovery: sbin/libm.so
[E] Copying from recovery: sbin/libminadbd.so
[E] Copying from recovery: sbin/libmincrypttwrp.so
[E] Copying from recovery: sbin/libminuitwrp.so
[E] Copying from recovery: sbin/libminzip.so
[E] Copying from recovery: sbin/libmmcutils.so
[E] Copying from recovery: sbin/libmtdutils.so
[E] Copying from recovery: sbin/libnetd_client.so
[E] Copying from recovery: sbin/libopenaes.so
[E] Copying from recovery: sbin/libpcre.so
[E] Copying from recovery: sbin/libpng.so
[E] Copying from recovery: sbin/libselinux.so
[E] Copying from recovery: sbin/libsparse.so
[E] Copying from recovery: sbin/libstdc++.so
[E] Copying from recovery: sbin/libstlport.so
[E] Copying from recovery: sbin/libtar.so
[E] Copying from recovery: sbin/libtwadbbu.so
[E] Copying from recovery: sbin/libtwrpmtp.so
[E] Copying from recovery: sbin/libunwind-ptrace.so
[E] Copying from recovery: sbin/libunwind.so
[E] Copying from recovery: sbin/libusbhost.so
[E] Copying from recovery: sbin/libutil-linux.so
[E] Copying from recovery: sbin/libutils.so
[E] Copying from recovery: sbin/libz.so
[E] Copying from recovery: sbin/linker
[E] Copying from recovery: sbin/ln
[E] Copying from recovery: sbin/load_policy
[E] Copying from recovery: sbin/losetup
[E] Copying from recovery: sbin/ls
[E] Copying from recovery: sbin/lsattr
[E] Copying from recovery: sbin/lsmod
[E] Copying from recovery: sbin/lspci
[E] Copying from recovery: sbin/lsusb
[E] Copying from recovery: sbin/lzcat
[E] Copying from recovery: sbin/lzma
[E] Copying from recovery: sbin/lzop
[E] Copying from recovery: sbin/lzopcat
[E] Copying from recovery: sbin/make_ext4fs
[E] Copying from recovery: sbin/man
[E] Copying from recovery: sbin/matchpathcon
[E] Copying from recovery: sbin/md5sum
[E] Copying from recovery: sbin/mesg
[E] Copying from recovery: sbin/mkdir
[E] Copying from recovery: sbin/mke2fs
[E] Copying from recovery: sbin/mkexfatfs
[E] Copying from recovery: sbin/mkfifo
[E] Copying from recovery: sbin/mkfs.ext2
[E] Copying from recovery: sbin/mkfs.f2fs
[E] Copying from recovery: sbin/mkfs.fat
[E] Copying from recovery: sbin/mknod
[E] Copying from recovery: sbin/mkswap
[E] Copying from recovery: sbin/mktemp
[E] Copying from recovery: sbin/modinfo
[E] Copying from recovery: sbin/modprobe
[E] Copying from recovery: sbin/more
[E] Copying from recovery: sbin/mount
[E] Copying from recovery: sbin/mount.exfat
[E] Copying from recovery: sbin/mountpoint
[E] Copying from recovery: sbin/mpstat
[E] Copying from recovery: sbin/mv
[E] Copying from recovery: sbin/nanddump
[E] Copying from recovery: sbin/nandwrite
[E] Copying from recovery: sbin/nbd-client
[E] Copying from recovery: sbin/nc
[E] Copying from recovery: sbin/netstat
[E] Copying from recovery: sbin/nice
[E] Copying from recovery: sbin/nmeter
[E] Copying from recovery: sbin/nohup
[E] Copying from recovery: sbin/nslookup
[E] Copying from recovery: sbin/ntpd
[E] Copying from recovery: sbin/od
[E] Copying from recovery: sbin/openaes
[E] Copying from recovery: sbin/openvt
[E] Copying from recovery: sbin/patch
[E] Copying from recovery: sbin/permissive.sh
[E] Copying from recovery: sbin/pgrep
[E] Copying from recovery: sbin/pidof
[E] Copying from recovery: sbin/pigz
[E] Copying from recovery: sbin/ping
[E] Copying from recovery: sbin/pipe_progress
[E] Copying from recovery: sbin/pkill
[E] Copying from recovery: sbin/pmap
[E] Copying from recovery: sbin/poweroff
[E] Copying from recovery: sbin/printenv
[E] Copying from recovery: sbin/printf
[E] Copying from recovery: sbin/ps
[E] Copying from recovery: sbin/pstree
[E] Copying from recovery: sbin/pwd
[E] Copying from recovery: sbin/pwdx
[E] Copying from recovery: sbin/r
[E] Copying from recovery: sbin/rdate
[E] Copying from recovery: sbin/rdev
[E] Copying from recovery: sbin/readlink
[E] Copying from recovery: sbin/realpath
[E] Copying from recovery: sbin/reboot
[E] Copying from recovery: sbin/recovery
[E] Copying from recovery: sbin/renice
[E] Copying from recovery: sbin/reset
[E] Copying from recovery: sbin/resize
[E] Copying from recovery: sbin/resize2fs
[E] Copying from recovery: sbin/restorecon
[E] Copying from recovery: sbin/rev
[E] Copying from recovery: sbin/rm
[E] Copying from recovery: sbin/rmdir
[E] Copying from recovery: sbin/rmmod
[E] Copying from recovery: sbin/route
[E] Copying from recovery: sbin/run-parts
[E] Copying from recovery: sbin/runcon
[E] Copying from recovery: sbin/rx
[E] Copying from recovery: sbin/sed
[E] Copying from recovery: sbin/selinuxenabled
[E] Copying from recovery: sbin/seq
[E] Copying from recovery: sbin/sestatus
[E] Copying from recovery: sbin/setconsole
[E] Copying from recovery: sbin/setenforce
[E] Copying from recovery: sbin/setfiles
[E] Copying from recovery: sbin/setkeycodes
[E] Copying from recovery: sbin/setprop
[E] Copying from recovery: sbin/setsebool
[E] Copying from recovery: sbin/setserial
[E] Copying from recovery: sbin/setsid
[E] Copying from recovery: sbin/sgdisk
[E] Copying from recovery: sbin/sh
[E] Copying from recovery: sbin/sha1sum
[E] Copying from recovery: sbin/sha256sum
[E] Copying from recovery: sbin/sha3sum
[E] Copying from recovery: sbin/sha512sum
[E] Copying from recovery: sbin/simg2img
[E] Copying from recovery: sbin/sleep
[E] Copying from recovery: sbin/smemcap
[E] Copying from recovery: sbin/sort
[E] Copying from recovery: sbin/split
[E] Copying from recovery: sbin/start
[E] Copying from recovery: sbin/stat
[E] Copying from recovery: sbin/stop
[E] Copying from recovery: sbin/strings
[E] Copying from recovery: sbin/stty
[E] Copying from recovery: sbin/sum
[E] Copying from recovery: sbin/swapoff
[E] Copying from recovery: sbin/swapon
[E] Copying from recovery: sbin/sync
[E] Copying from recovery: sbin/sysctl
[E] Copying from recovery: sbin/tac
[E] Copying from recovery: sbin/tail
[E] Copying from recovery: sbin/tar
[E] Copying from recovery: sbin/taskset
[E] Copying from recovery: sbin/teamwin
[E] Copying from recovery: sbin/tee
[E] Copying from recovery: sbin/telnet
[E] Copying from recovery: sbin/telnetd
[E] Copying from recovery: sbin/test
[E] Copying from recovery: sbin/tftp
[E] Copying from recovery: sbin/tftpd
[E] Copying from recovery: sbin/time
[E] Copying from recovery: sbin/timeout
[E] Copying from recovery: sbin/toolbox
[E] Copying from recovery: sbin/top
[E] Copying from recovery: sbin/touch
[E] Copying from recovery: sbin/tr
[E] Copying from recovery: sbin/traceroute
[E] Copying from recovery: sbin/true
[E] Copying from recovery: sbin/ttysize
[E] Copying from recovery: sbin/tune2fs
[E] Copying from recovery: sbin/twrp
[E] Copying from recovery: sbin/ueventd
[E] Copying from recovery: sbin/umount
[E] Copying from recovery: sbin/uname
[E] Copying from recovery: sbin/uncompress
[E] Copying from recovery: sbin/unexpand
[E] Copying from recovery: sbin/uniq
[E] Copying from recovery: sbin/unix2dos
[E] Copying from recovery: sbin/unlzma
[E] Copying from recovery: sbin/unlzop
[E] Copying from recovery: sbin/unpigz
[E] Copying from recovery: sbin/unxz
[E] Copying from recovery: sbin/unzip
[E] Copying from recovery: sbin/uptime
[E] Copying from recovery: sbin/usleep
[E] Copying from recovery: sbin/uudecode
[E] Copying from recovery: sbin/uuencode
[E] Copying from recovery: sbin/vi
[E] Copying from recovery: sbin/watch
[E] Copying from recovery: sbin/watchdogd
[E] Copying from recovery: sbin/wc
[E] Copying from recovery: sbin/wget
[E] Copying from recovery: sbin/which
[E] Copying from recovery: sbin/whoami
[E] Copying from recovery: sbin/xargs
[E] Copying from recovery: sbin/xz
[E] Copying from recovery: sbin/xzcat
[E] Copying from recovery: sbin/yes
[E] Copying from recovery: sbin/zcat
[D] [Installer] Retrieve install type stage
[V] ROM ID: dual
[V] - /system: /system/multiboot/dual/system
[V] - /cache: /cache/multiboot/dual/cache
[V] - /data: /data/multiboot/dual/data
[V] - System is image file: false
[V] - Cache is image file: false
[V] - Data is image file: false
[V] ROM ID: dual
[D] [Installer] Chroot set up stage
[D] Boot partition SHA512sum: a757a2f6d219ad2c458e49190d7d23b6b0736487c2d59d8e632b4f4e8936c4db90fc5da32b1b87435650b2562e42dee0ba75950ab2e11a93b95ced171de8094a
[V] Won't switch to non-existent target ROM
[D] [Installer] Filesystem mounting stage
[E] There is not enough space to create /data/.system.img.tmp
[E] - Needed:    1879048192 bytes
[E] - Available: 1776603136 bytes
[V] 
[V] There is not enough space to create /data/.system.img.tmp
[V] - Needed:    1879048192 bytes
[V] - Available: 1776603136 bytes
[V] Failed to create temporary image /data/.system.img.tmp
[V] Trying to create temporary image on external SD
[V] (This will be slow)
[D] /storage/sdcard1/.system.img.tmp: Creating new 1879048192 ext4 image
[D] Running executable: make_ext4fs
[V] Copying system to temporary image
[D] Assigning /storage/sdcard1/.system.img.tmp to loop device /dev/block/loop17
[D] Clearing loop device /dev/block/loop17
[D] [Installer] Installation stage
[D] Property 'ro.product.device' does not exist in recovery's default.prop
[D] - 'ro.product.device'='Y635-L01' will be set in chroot environment
[D] Property 'ro.build.product' does not exist in recovery's default.prop
[D] - 'ro.build.product'='Y635-L01' will be set in chroot environment
[D] Property 'ro.bootloader' does not exist in recovery's default.prop
[D] - 'ro.bootloader'='unknown' will be set in chroot environment
[V] Running real update-binary
[V] Here we go!
[D] update-binary is AROMA: 0
[D] Original properties environment: 10,0
[D] Switched to legacy properties environment: 9,32768
Target: 1474041668
Target: 1474041668about to run program [/update-binary-tool] with 3 args
[D] update-binary-tool: Successfully mounted /mb/loop.system at /system
about to run program [/tmp/install/bin/backuptool.sh] with 2 args
run_program: child exited with status 127
about to run program [/update-binary-tool] with 3 args
[D] update-binary-tool: Successfully unmounted /system
about to run program [/update-binary-tool] with 3 args
[D] update-binary-tool: Successfully mounted /mb/bind.data at /data
about to run program [/tmp/install/bin/otasigcheck.sh] with 1 args
grep: /tmp/recovery.log: No such file or directory
grep: /tmp/recovery.log: No such file or directory
about to run program [/update-binary-tool] with 3 args
[D] update-binary-tool: Successfully unmounted /data
Patching system image unconditionally...
Verifying the updated system image...
Patching system image unconditionally...performing update
open "/dev/block/bootdevice/by-name/system" failed: No such file or directory
Verifying the updated system image...script aborted: system partition has unexpected contents after OTA update
[D] Updater exited with status: 7

[V] Elapsed time: 0:00min
[V] Failed to run real update-binary
[D] Running executable: /update-binary-tool
[D] update-binary-tool: Successfully mounted /mb/loop.system at /system
[D] [Installer] Filesystem unmounting stage
[D] Running executable: /update-binary-tool
[D] update-binary-tool: Successfully unmounted /system
[D] Running executable: /update-binary-tool
[E] update-binary-tool: /cache: Failed to unmount: Invalid argument
[D] Running executable: /update-binary-tool
[E] update-binary-tool: /data: Failed to unmount: Invalid argument
[V] Copying temporary image to system
[D] Assigning /storage/sdcard1/.system.img.tmp to loop device /dev/block/loop17
[D] Clearing loop device /dev/block/loop17
[D] [Installer] Cleanup stage
[V] Failed to flash zip file.
[V] Destroying chroot environment
[E] Failed to unmount /chroot/system: Invalid argument
[E] Failed to unmount /chroot/cache: Invalid argument
[E] Failed to unmount /chroot/data: Invalid argument
[E] Failed to unmount /chroot/efs: Invalid argument
[E] Failed to unmount /chroot: Device or resource busy
[D] Attempting to unmount /chroot/mb/install.zip
[D] Attempting to unmount /chroot/mb/bind.data
[D] Attempting to unmount /chroot/mb/bind.cache
[D] Attempting to unmount /chroot
[E] /efs is not mounted
[V] The log file was saved as MultiBoot.log on the internal storage.
[V] Finished cleanup
```

I think this is the error:

```
Patching system image unconditionally...
Verifying the updated system image...
Patching system image unconditionally...performing update
open "/dev/block/bootdevice/by-name/system" failed: No such file or directory
Verifying the updated system image...script aborted: system partition has unexpected contents after OTA update
[D] Updater exited with status: 7
```

Adding /dev/block/bootdevice/by-name/system to the extra partitions could be the solution?

**Comment by R4G2R** [comment]
Please make another build @chenxiaolong

**Comment by webmaster33** [comment]
This is the error reason:
[E] There is not enough space to create /data/.system.img.tmp
[E] - Needed:    1879048192 bytes
[E] - Available: 1776603136 bytes

You don't have enough space on /data.

**Comment by webmaster33** [comment]
Also did you patch the OTA file?

**Comment by R4G2R** [comment]
Patch the otra file, how?

**Comment by R4G2R** [comment]
Patch de ota file, how?

**Comment by webmaster33** [comment]
In CM13, the OTA zip file is downloaded to internal sdcard / cmupdater. 
Then I copy out from there, patching, then flashing manually through recovery.

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

_(This is a message for the build server.)_

@R4G2R It looks like you don't have enough space on /data. Due to how CM (and other Lollipop images) ships a system image, it needs to create a temporary ext4 image in /data to flash the ROM.

```
[E] There is not enough space to create /data/.system.img.tmp
[E] - Needed:    1879048192 bytes
[E] - Available: 1776603136 bytes
```

Based on the error, you need around ~100MiB more space.

**Comment by R4G2R** [comment]
I can't fix it. I close the pull request.

**Pull request closed without merging**
