### PR TITLE
libmbp: Update for Pantech device

### PR DESCRIPTION
**Pull request by chautruongthinh**
libmbp: Fix correct name of Pantech device 			
libmbp: Reinitial attempt at VEGA IRON & VEGA IRON2 Boot UI support

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Comment by chautruongthinh** [comment]
screenshot_2016-07-03-14-14-03
I tested!!!

**Comment by chenxiaolong** [comment]
Merged, thank you!

**Comment by chautruongthinh** [comment]
Thanks your support!!

**Pull request merged**
