### PR TITLE
Update polish language

### PR DESCRIPTION
**Pull request by MisiekDP**
Update polish words.

### CODE REVIEW

**Comment by MisiekDP** [comment]
I am not an admin but I can verify :D 
Btw. could you create a menu with a choice of language in settings?

**Comment by chenxiaolong** [comment]
@MisiekDP Thanks for the PR! Would you mind making the changes at Transifex instead? https://www.transifex.com/dualbootpatcher/dualbootpatcher/

**Comment by MisiekDP** [comment]
Sure, I updated now polish language :) You can update it if you can. Thanks! :)

**Comment by chenxiaolong** [comment]
Done, thank you! #722

**Comment by Dinolek** [comment]
@chenxiaolong Hello,
I fixed Polish translation little bit more.
Can you look at this?

**Comment by chenxiaolong** [comment]
@Dinolek Done. #739

**Comment by Dinolek** [comment]
@chenxiaolong Thanks.

**Pull request closed without merging**
