### PR TITLE
Unified DBP for 2gb and 3gb Variant of Lenovo k4 and minor mistakes Improved Plz add support 😃😃😃😃

### PR DESCRIPTION
**Pull request by dg28gadhavi**
Plz verify the patch for k4 note support and merge it sir plz and make a snapshot version out of it asap so i can dual boot

### CODE REVIEW

**Comment by dg28gadhavi** [comment]
@chenxiaolong plz verify and merge my patch for Lenovo k4 support

**Comment by dg28gadhavi** [comment]
Unified DBP for 2gb and 3Gb also corrected partition defining mistakes now it will work perfectly fine😃😃😃

**Comment by dg28gadhavi** [comment]
Sorry but added missing hyphen 😅😅😅

**Comment by dg28gadhavi** [comment]
Added all possible codenames from different roms

**Comment by chenxiaolong** [comment]
@chenxiaolong-bot test this please

**Pull request merged**
